"use client";

import { useCallback, useEffect } from "react";
import { useMutation, useQuery } from "convex/react";
import { api } from "../../convex/_generated/api";
import type { Id } from "../../convex/_generated/dataModel";

export type Milestone = { _id: Id<"milestones">; text: string; done: boolean; order: number };

// Progressive, concrete, verifiable milestones per skill.
// Each list: ~30% basics → ~40% real usage → ~30% production / scale.
// Last entry is always a ship/build-to-production checkpoint.

export const DEFAULT_MILESTONES: Record<string, string[]> = {
  // ─── Languages ─────────────────────────────────────────────────────
  Python: [
    "Syntax + data structures (list, dict, set, tuple)",
    "Functions, comprehensions, lambdas, *args/**kwargs",
    "OOP: classes, dataclasses, dunder methods",
    "Modules + virtualenv + pip / uv",
    "File I/O, JSON, pathlib, requests",
    "Type hints + mypy or pyright",
    "Logging + structured errors (no bare except)",
    "Write pytest unit + parametrized tests",
    "Lint with ruff, format with black",
    "Profile with cProfile, fix one bottleneck",
    "Package + publish to PyPI or private index",
    "Ship a CLI or API to production",
  ],
  JavaScript: [
    "Variables, data types, operators",
    "Functions, scope, closures, this",
    "Arrays + objects, destructuring",
    "Modules + ES6+ syntax",
    "DOM events + form handling",
    "Async: callbacks → promises → async/await",
    "Fetch API + error handling",
    "Iterators, generators, Symbol",
    "Set up ESLint + Prettier in a project",
    "Write Vitest or Jest unit tests",
    "Read + tune Chrome DevTools performance trace",
    "Ship a small SPA without a framework",
  ],
  TypeScript: [
    "Basic types + interfaces + type aliases",
    "Unions, narrowing, type guards",
    "Generics + constraints",
    "Utility types (Partial, Pick, Record, Omit)",
    "Discriminated unions + exhaustive switch",
    "Configure strict tsconfig + noUncheckedIndexedAccess",
    "Type a fetch wrapper with generics",
    "Use zod or valibot for runtime validation",
    "Author + publish a typed npm package",
    "Migrate a JS project to strict TS",
    "Set up tsc + ESLint type-aware rules in CI",
    "Ship a TS app with end-to-end type safety",
  ],
  Java: [
    "Syntax + primitives + control flow",
    "OOP: classes, inheritance, interfaces, records",
    "Collections framework + iterators",
    "Generics, bounded type params",
    "Streams + lambdas",
    "Exceptions + try-with-resources",
    "Maven or Gradle project structure",
    "JUnit 5 + Mockito tests",
    "Concurrency: threads, executors, CompletableFuture",
    "Profile with JFR, tune GC basics",
    "Package as runnable JAR + Docker image",
    "Ship a Spring Boot REST API to prod",
  ],
  "C++": [
    "Syntax + references vs pointers",
    "RAII + smart pointers (unique, shared)",
    "STL containers + iterators + algorithms",
    "Templates + concepts (C++20)",
    "Move semantics + rvalue refs",
    "Lambdas + std::function",
    "CMake project layout",
    "Unit tests with Catch2 or GoogleTest",
    "Sanitizers (ASan, UBSan) in build",
    "Profile with perf or VTune",
    "Cross-compile + static analysis (clang-tidy)",
    "Ship a small native tool or game",
  ],
  "C#": [
    "Syntax + value vs reference types",
    "OOP + interfaces + records",
    "LINQ + delegates + events",
    "Async/await + Task + CancellationToken",
    "NuGet + .csproj + SDK-style projects",
    "xUnit + Moq tests",
    "Nullable reference types enabled",
    "EF Core basics + migrations",
    "Dependency injection container",
    "Configure CI build + dotnet format",
    "Publish trimmed self-contained binary",
    "Ship an ASP.NET Core Web API to prod",
  ],
  Go: [
    "Syntax + structs + interfaces",
    "Slices, maps, strings idioms",
    "Goroutines + channels + select",
    "Context for cancellation + timeouts",
    "Error wrapping (errors.Is/As)",
    "Modules + go.mod + workspaces",
    "Table-driven tests + go test -race",
    "stdlib net/http + middleware patterns",
    "Profile with pprof + go tool trace",
    "Lint with golangci-lint",
    "Build small + static binary with -trimpath",
    "Ship an HTTP service to production",
  ],
  Rust: [
    "Syntax + ownership + borrowing",
    "Lifetimes in functions + structs",
    "Enums + pattern matching + Result/Option",
    "Traits + generics + trait objects",
    "Modules + crates + workspace layout",
    "Cargo + clippy + rustfmt in CI",
    "Unit + integration tests + cargo test",
    "Async + tokio + select! basics",
    "Error handling with thiserror / anyhow",
    "Unsafe basics + when to avoid",
    "Profile + benchmark with criterion",
    "Ship a CLI or web service to prod",
  ],
  Ruby: [
    "Syntax + blocks + iterators + Enumerable",
    "OOP + modules + mixins",
    "Gems + Bundler + Gemfile.lock",
    "RSpec or Minitest unit tests",
    "Rubocop + standard style",
    "Debug with pry / byebug",
    "ActiveRecord or Sequel basics",
    "Background jobs (Sidekiq) basics",
    "Profile memory + GC stats",
    "Package + publish a gem",
    "Ship a Rails or Sinatra app to prod",
  ],
  PHP: [
    "Syntax + arrays + null + types",
    "OOP + namespaces + autoloading (PSR-4)",
    "Composer + lock file workflow",
    "PDO + prepared statements (no SQLi)",
    "PHPUnit tests + Mockery",
    "PSR-12 style + PHPStan static analysis",
    "Sessions + cookies + CSRF defenses",
    "Caching (OPcache, APCu) basics",
    "Logging + Monolog + error handler",
    "Containerize PHP-FPM + Nginx",
    "Ship a Laravel or vanilla MVC app to prod",
  ],
  Kotlin: [
    "Syntax + null safety + smart casts",
    "Data classes + sealed classes",
    "Coroutines + structured concurrency",
    "Flow + StateFlow basics",
    "Gradle Kotlin DSL project layout",
    "JUnit 5 + MockK tests",
    "Detekt + ktlint in CI",
    "Build an Android or Ktor app",
    "Multiplatform basics (KMP) overview",
    "Profile with Android Studio profiler",
    "Publish to Play Store or Maven Central",
    "Ship a Kotlin service or app to prod",
  ],
  Swift: [
    "Syntax + optionals + value types",
    "Protocols + protocol extensions",
    "Generics + where clauses",
    "SwiftUI views + state + bindings",
    "Combine or async/await + actors",
    "SwiftData or Core Data basics",
    "XCTest unit + UI tests",
    "Dependency injection patterns",
    "Instruments profiling (Time, Allocations)",
    "Code signing + provisioning workflow",
    "TestFlight beta distribution",
    "Ship an iOS app to App Store",
  ],
  Scala: [
    "Syntax + immutability + val/var/def",
    "Case classes + pattern matching",
    "Higher-order functions + collections",
    "Option / Either / Try for errors",
    "Implicits / given (Scala 3)",
    "sbt + multi-module builds",
    "ScalaTest or MUnit tests",
    "Akka or ZIO basics for concurrency",
    "Cats / Cats Effect intro",
    "Profile with async-profiler",
    "Package fat JAR + run on JVM cluster",
    "Ship a Scala service to prod",
  ],
  SQL: [
    "SELECT, WHERE, ORDER BY, LIMIT",
    "JOINs (inner, left, right, full)",
    "GROUP BY + aggregations + HAVING",
    "Subqueries + CTEs",
    "Window functions (ROW_NUMBER, LAG, etc.)",
    "Indexes (B-tree, partial, composite)",
    "Read EXPLAIN / EXPLAIN ANALYZE",
    "Transactions + isolation levels",
    "Schema design + normalization vs denorm",
    "Avoid N+1 + understand query plans",
    "Backup + restore + point-in-time recovery",
    "Ship a real reporting query against prod-like data",
  ],
  Bash: [
    "Variables + quoting rules",
    "Pipes + redirection + here-docs",
    "Loops + conditionals + case",
    "Functions + arguments + return codes",
    "Arrays + parameter expansion",
    "Process substitution + xargs + find",
    "set -euo pipefail + trap discipline",
    "ShellCheck clean code",
    "Signals + traps + cleanup on exit",
    "Argument parsing with getopts",
    "Package a script with man-page + install",
    "Ship a real ops or backup script in prod",
  ],

  // ─── Backend frameworks ────────────────────────────────────────────
  FastAPI: [
    "Path + query + body params",
    "Pydantic request/response models",
    "Dependency injection (Depends)",
    "Async endpoints + concurrency basics",
    "DB integration (SQLAlchemy 2.x / async)",
    "Auth: OAuth2 password bearer + JWT",
    "Background tasks + BackgroundTasks",
    "OpenAPI customization + tags",
    "Testing with TestClient + pytest fixtures",
    "Logging + structured errors + Sentry",
    "Containerize + gunicorn/uvicorn workers",
    "Ship a FastAPI service to production",
  ],
  Django: [
    "Project + app layout + settings split",
    "Models + migrations + custom managers",
    "ORM querysets + select_related/prefetch",
    "Views (FBV + CBV) + URL routing",
    "Templates + forms + ModelForm",
    "Admin site customization",
    "Auth + permissions + signals",
    "DRF: serializers, viewsets, routers",
    "Testing: pytest-django + factories",
    "Caching (Memcached/Redis) + low-level cache",
    "Static + media + S3 storage",
    "Ship a Django app behind gunicorn + nginx",
  ],
  Flask: [
    "App factory pattern",
    "Routing + Jinja templates",
    "Blueprints + extensions architecture",
    "Flask-SQLAlchemy + migrations",
    "Forms (Flask-WTF) + CSRF",
    "Auth (Flask-Login or JWT)",
    "Testing with pytest + test client",
    "Background tasks (Celery / RQ)",
    "Logging + Sentry integration",
    "Deploy behind gunicorn + nginx",
    "Containerize with multi-stage Dockerfile",
    "Ship a Flask app to production",
  ],
  "Node.js": [
    "Modules + npm/pnpm + lockfile",
    "Async patterns + streams + backpressure",
    "Event loop + microtasks + nextTick",
    "REST API with Express or Fastify",
    "Auth: sessions vs JWT trade-offs",
    "Connect to Postgres / Mongo",
    "Validate input (zod / joi) at the edge",
    "Logging (pino) + correlation IDs",
    "Unit + integration tests (vitest/jest)",
    "Cluster / worker_threads for CPU work",
    "Containerize + healthchecks",
    "Ship a Node service to production",
  ],
  Express: [
    "Routing + path params + middleware",
    "Request/response lifecycle",
    "Body parsing + cookies + sessions",
    "Error-handling middleware (4-arg)",
    "Auth with Passport or JWT",
    "Input validation (zod / joi)",
    "Rate limiting + CORS configured right",
    "Helmet + secure HTTP headers",
    "Integration tests with supertest",
    "Structured logging + access logs",
    "Graceful shutdown + signal handling",
    "Ship an Express API to production",
  ],
  NestJS: [
    "Modules + controllers + providers",
    "Dependency injection container",
    "Pipes, guards, interceptors, filters",
    "Validation with class-validator + DTOs",
    "TypeORM or Prisma integration",
    "Auth with Passport + JWT",
    "Microservices transports (TCP, NATS, Kafka)",
    "WebSockets gateway",
    "OpenAPI module (Swagger) auto-gen",
    "Unit + e2e tests with @nestjs/testing",
    "Containerize + multi-stage build",
    "Ship a NestJS service to production",
  ],
  Spring: [
    "Spring Boot starter project",
    "Dependency injection + @Component scan",
    "REST controllers + validation",
    "Spring Data JPA + repositories",
    "Spring Security + JWT or OAuth2",
    "Profiles + externalized config",
    "Caching (@Cacheable) + Redis",
    "Actuator + metrics + tracing",
    "JUnit + Testcontainers integration tests",
    "Native image with GraalVM (optional)",
    "Containerize + Kubernetes-friendly probes",
    "Ship a Spring Boot service to prod",
  ],
  Rails: [
    "MVC + convention over config",
    "Generators + migrations + schema.rb",
    "ActiveRecord queries + associations",
    "Routing + RESTful resources + nested routes",
    "Action Mailer + Active Job",
    "Sidekiq background workers",
    "Hotwire / Turbo / Stimulus basics",
    "RSpec or Minitest + system tests",
    "Strong params + CSRF + secure defaults",
    "Caching (Russian doll, fragment)",
    "Deploy with Kamal or Heroku-style PaaS",
    "Ship a Rails app to production",
  ],
  Laravel: [
    "Routes + controllers + middleware",
    "Eloquent ORM + relationships + eager load",
    "Blade templates + components",
    "Migrations + seeders + factories",
    "Auth scaffolding (Breeze / Jetstream)",
    "Form requests + validation",
    "Queues + jobs (Redis / SQS)",
    "Events + listeners + broadcasting",
    "Pest or PHPUnit tests + factories",
    "Caching + Redis sessions",
    "Deploy with Forge / Vapor / Docker",
    "Ship a Laravel app to production",
  ],
  "ASP.NET": [
    "Minimal APIs vs Controllers trade-offs",
    "Dependency injection container",
    "Entity Framework Core + migrations",
    "Authentication + Identity + JWT",
    "Authorization policies + claims",
    "Background services + IHostedService",
    "Logging + OpenTelemetry",
    "Health checks + readiness probes",
    "xUnit + WebApplicationFactory tests",
    "API versioning + OpenAPI / Swashbuckle",
    "Containerize + publish trimmed binary",
    "Ship an ASP.NET Core API to prod",
  ],
  GraphQL: [
    "Schema + types + resolvers",
    "Queries vs mutations vs subscriptions",
    "Pagination (Relay cursors)",
    "N+1 + DataLoader pattern",
    "Auth + field-level authorization",
    "Persisted queries + query depth limits",
    "Federation or schema stitching basics",
    "Caching (CDN + client) for GraphQL",
    "Error handling conventions",
    "Schema diffing in CI + breaking-change checks",
    "Tracing + Apollo Studio / GraphOS",
    "Ship a GraphQL API to production",
  ],
  gRPC: [
    "Protocol Buffers + .proto schema",
    "Unary + server / client / bidi streaming",
    "Generate stubs across languages",
    "Interceptors + metadata",
    "Deadlines + cancellation",
    "TLS + auth (mTLS or token)",
    "Health checks + reflection service",
    "Error model (status codes + details)",
    "Load balancing (xDS or proxyless)",
    "Backward-compatible schema evolution",
    "Tracing (OTel) across services",
    "Ship a gRPC service to production",
  ],
  REST: [
    "Resource-oriented URLs",
    "HTTP methods + status codes (right ones)",
    "Idempotency + safety semantics",
    "Pagination, filtering, sorting conventions",
    "Versioning strategy (URL vs header)",
    "Authn + Authz (OAuth2 / JWT)",
    "Rate limiting + caching headers",
    "Validation + consistent error envelopes",
    "OpenAPI / Swagger source of truth",
    "Contract tests (schemathesis / pact)",
    "Observability: logs, metrics, traces",
    "Ship a versioned REST API to prod",
  ],

  // ─── Frontend ──────────────────────────────────────────────────────
  React: [
    "Components + JSX + props",
    "State with useState + lifting state",
    "useEffect lifecycle + cleanups",
    "Lists, keys, conditional rendering",
    "Forms + controlled inputs",
    "Context + custom hooks",
    "useMemo / useCallback / useRef when needed",
    "Data fetching (TanStack Query)",
    "Routing (TanStack Router or React Router)",
    "Error boundaries + Suspense",
    "Profile + fix re-render hotspots",
    "Ship a real React app to production",
  ],
  "Next.js": [
    "App router file conventions",
    "Server vs Client components",
    "Layouts + loading.tsx + error.tsx",
    "Data fetching + caching + revalidation",
    "Route handlers + Server Actions",
    "Middleware + edge runtime constraints",
    "next/image + next/font optimization",
    "Auth (NextAuth / Clerk / custom)",
    "ISR / PPR / streaming concepts",
    "Playwright e2e tests",
    "Bundle analyzer + Core Web Vitals tuning",
    "Ship a Next.js app to Vercel prod",
  ],
  Vue: [
    "Template syntax + directives",
    "Reactivity (ref / reactive / computed)",
    "Composition API + script setup",
    "Components + props + emits + slots",
    "Pinia state management",
    "Vue Router + nested routes",
    "Composables / shared logic",
    "Form handling + validation",
    "Suspense + async components",
    "Vitest + Vue Test Utils",
    "Build + deploy a Vue SPA",
    "Ship a Vue app to production",
  ],
  Nuxt: [
    "Pages + auto-routing",
    "Layouts + middleware",
    "useFetch / useAsyncData",
    "Server routes (Nitro)",
    "Auto-imports + composables",
    "SSR vs ISR vs SSG choice",
    "Modules ecosystem (auth, content, image)",
    "State (Pinia) + cookies",
    "SEO meta + sitemap",
    "Image + font + script optimization",
    "Deploy to Vercel / Netlify / Node server",
    "Ship a Nuxt app to production",
  ],
  Angular: [
    "Components + templates + bindings",
    "Modules vs standalone components",
    "Services + DI hierarchy",
    "HttpClient + interceptors",
    "RxJS observables + operators",
    "Reactive forms + validators",
    "Router + lazy loading + guards",
    "Signals (Angular 17+)",
    "Karma/Jasmine or Jest tests",
    "Change detection strategy + OnPush",
    "Build + budgets + i18n",
    "Ship an Angular app to production",
  ],
  Svelte: [
    "Reactivity primitives ($state, $derived)",
    "Component composition + props",
    "Stores + context",
    "SvelteKit routing + load functions",
    "Form actions + server endpoints",
    "Transitions + animations",
    "+server / API handlers",
    "Adapters (Vercel, Node, static)",
    "Vitest + Playwright tests",
    "Image + asset optimization",
    "Deploy SvelteKit app",
    "Ship a SvelteKit app to production",
  ],
  HTML: [
    "Semantic tags + document outline",
    "Forms + inputs + native validation",
    "Accessibility basics (ARIA, alt, labels)",
    "Landmark roles + keyboard navigation",
    "SEO meta tags + canonical",
    "Open Graph + Twitter cards",
    "Structured data (JSON-LD)",
    "Responsive images (srcset, picture)",
    "Performance: defer/async scripts",
    "Lighthouse audit clean",
    "Validate with W3C validator",
    "Ship an accessible static page",
  ],
  CSS: [
    "Selectors + specificity + cascade",
    "Box model + display modes",
    "Flexbox layout",
    "Grid layout + named areas",
    "Responsive design + media queries",
    "Container queries + :has()",
    "Custom properties (CSS vars)",
    "Animations + transitions",
    "Logical properties + RTL support",
    "Dark mode via prefers-color-scheme",
    "Lint with Stylelint",
    "Ship a pixel-accurate responsive layout",
  ],
  Tailwind: [
    "Utility-first mindset",
    "Responsive prefixes",
    "Variants (hover, focus, dark, group)",
    "tailwind.config.js theme + plugins",
    "Extract repeats with @apply or components",
    "Arbitrary values + JIT",
    "Dark mode toggle",
    "Pair with Headless UI / Radix",
    "Optimize content paths (no bloat)",
    "Set up Prettier plugin for class sort",
    "Themed design tokens via CSS vars",
    "Ship a Tailwind UI to production",
  ],
  Sass: [
    "Variables + nesting",
    "Mixins + @include + @function",
    "Partials + @use / @forward (modern)",
    "Maps + lists + control flow",
    "Build pipeline (dart-sass)",
    "BEM + 7-1 architecture",
    "Source maps + Stylelint",
    "Refactor a CSS project to SCSS",
    "Ship an SCSS-built design system",
  ],
  Redux: [
    "Store + actions + reducers",
    "Redux Toolkit (createSlice, createReducer)",
    "Async with createAsyncThunk",
    "RTK Query for server state",
    "Selectors + reselect memoization",
    "Middleware + listeners",
    "Normalized state shape",
    "DevTools + time-travel debugging",
    "Migrate legacy Redux to RTK",
    "Test reducers + thunks",
    "Persist state (redux-persist)",
    "Ship an RTK-backed app to production",
  ],
  Vite: [
    "Dev server + HMR",
    "Build + bundle output",
    "Plugins + config",
    "Env vars + modes",
    "Path aliases + tsconfig paths",
    "CSS modules + PostCSS + Tailwind",
    "Library mode (build a lib)",
    "Optimize deps + pre-bundling",
    "Migrate a CRA project to Vite",
    "Bundle analyzer (rollup-plugin-visualizer)",
    "Production build + cache-busting",
    "Ship a Vite app to production",
  ],
  Webpack: [
    "Entry, output, loaders, plugins",
    "Code splitting + dynamic imports",
    "DevServer + HMR",
    "Tree shaking + sideEffects flag",
    "Source maps + production maps",
    "Babel + TypeScript loaders",
    "Module Federation overview",
    "Asset modules + image optimization",
    "Performance budgets + bundle analyzer",
    "Cache strategy (contenthash) + CDN",
    "Migrate a Webpack 4 → 5 project",
    "Ship a Webpack-built app to production",
  ],

  // ─── Databases ─────────────────────────────────────────────────────
  PostgreSQL: [
    "psql + connection basics",
    "Schema design + constraints + FKs",
    "Indexes (B-tree, GIN, BRIN, partial)",
    "EXPLAIN ANALYZE + buffers",
    "Transactions + isolation levels (MVCC)",
    "JSONB + full-text search",
    "Window functions + CTEs",
    "Partitioning + table inheritance",
    "Logical + streaming replication",
    "Backups + pg_dump + PITR",
    "Tune autovacuum + work_mem + shared_buffers",
    "Ship a Postgres-backed service to prod",
  ],
  MySQL: [
    "Connect + basic CRUD",
    "Schema + storage engines (InnoDB)",
    "Indexes + composite + covering",
    "EXPLAIN + slow query log",
    "Transactions + isolation (REPEATABLE READ)",
    "Replication (async + group)",
    "Backups (mysqldump + xtrabackup)",
    "Connection pooling + max_connections",
    "Read-replica routing",
    "Online schema change (gh-ost / pt-osc)",
    "Monitor (Performance Schema)",
    "Ship a MySQL-backed app to prod",
  ],
  SQLite: [
    "File-based DB workflow",
    "Schema + WAL mode",
    "Indexes + ANALYZE",
    "Transactions + busy timeout",
    "Full-text search (FTS5)",
    "JSON1 extension basics",
    "Backup + VACUUM",
    "Concurrency limits + alternatives",
    "Embed in app (Python/Node/Go)",
    "Ship an app using SQLite (e.g. Litestream replication)",
  ],
  MongoDB: [
    "Documents + collections",
    "CRUD + aggregation pipeline",
    "Indexes + compound + multikey + text",
    "Schema design (embed vs reference)",
    "Transactions in replica sets",
    "Change Streams",
    "Replica sets + read preference",
    "Sharding strategy + shard keys",
    "Backups (mongodump + Atlas snapshots)",
    "Atlas Search basics",
    "Profile slow queries with explain()",
    "Ship a Mongo-backed service to prod",
  ],
  Redis: [
    "Strings, hashes, lists, sets, sorted sets",
    "Expiration + TTL + keyspace notifications",
    "Pub/Sub + Streams",
    "Persistence (RDB vs AOF)",
    "Pipelining + transactions (MULTI)",
    "Lua scripts + atomic ops",
    "Caching patterns (cache-aside, write-through)",
    "Rate limiting with INCR + EXPIRE",
    "Eviction policies + memory tuning",
    "Cluster + sentinel basics",
    "Redis as a queue (BullMQ / RSMQ)",
    "Ship Redis-backed cache to production",
  ],
  Elasticsearch: [
    "Index + mapping + analyzers",
    "Document CRUD + bulk API",
    "Query DSL (match, term, bool)",
    "Aggregations (metric + bucket)",
    "Relevance tuning + boosting",
    "Index templates + ILM policies",
    "Bulk indexing + reindex API",
    "Cluster + shards + replicas",
    "Snapshots + restore",
    "Monitoring (Kibana stack)",
    "Search-as-you-type + suggesters",
    "Ship a search feature to production",
  ],
  Cassandra: [
    "Wide-column data model",
    "Partition + clustering keys",
    "CQL basics",
    "Consistency levels + tunable consistency",
    "Compaction strategies",
    "Repair + nodetool basics",
    "Backup + snapshot",
    "Modeling for queries (denormalize)",
    "Time-series + TTL data",
    "Materialized views + secondary indexes",
    "Ship a Cassandra-backed service to prod",
  ],
  DynamoDB: [
    "Single-table design",
    "Partition + sort keys",
    "GSIs + LSIs",
    "Query vs Scan + cost",
    "PutItem / UpdateItem / TransactWriteItems",
    "Streams + Lambda triggers",
    "On-demand vs provisioned + autoscaling",
    "Hot partition diagnosis",
    "Backups + PITR",
    "DAX caching for reads",
    "Adjacency list / hierarchical models",
    "Ship a serverless app with DynamoDB",
  ],
  "SQL Server": [
    "T-SQL basics + system functions",
    "Schema design + constraints",
    "Stored procedures + functions + CTEs",
    "Indexes + execution plans",
    "Statistics + query store",
    "Transactions + isolation + RCSI",
    "Backups (full / diff / log)",
    "Always On availability groups",
    "SQL Agent jobs + maintenance plans",
    "Migrate or replicate to Azure SQL",
    "Tune slow queries with DMVs",
    "Ship a SQL Server-backed app to prod",
  ],

  // ─── Cloud ─────────────────────────────────────────────────────────
  AWS: [
    "IAM users + roles + policies (least priv)",
    "VPC + subnets + security groups",
    "S3 buckets + lifecycle + versioning",
    "EC2 instances + ASG + ALB",
    "RDS basics + parameter groups",
    "Lambda + API Gateway + EventBridge",
    "CloudWatch logs + metrics + alarms",
    "Secrets Manager + SSM Parameter Store",
    "Cost Explorer + budgets + tags",
    "Infra as code with Terraform / CDK",
    "Backup + DR strategy",
    "Ship a multi-AZ workload to AWS",
  ],
  GCP: [
    "Projects + folders + IAM",
    "Cloud Storage buckets + lifecycle",
    "Compute Engine vs Cloud Run vs GKE",
    "Cloud SQL + Cloud Spanner overview",
    "Cloud Functions + Cloud Run triggers",
    "VPC + firewall rules + Cloud NAT",
    "Logging + Cloud Monitoring + Trace",
    "Secret Manager + IAM workload identity",
    "Cloud Build + Artifact Registry",
    "Billing + budgets + alerts",
    "Terraform for GCP",
    "Ship an app to Cloud Run + Cloud SQL",
  ],
  Azure: [
    "Subscriptions + resource groups + tags",
    "Storage accounts + blobs + tiers",
    "App Service vs Functions vs AKS",
    "Azure SQL + Cosmos DB",
    "Entra ID + RBAC",
    "VNets + NSGs + Private Endpoints",
    "Azure Monitor + Log Analytics",
    "Key Vault + managed identities",
    "Bicep or Terraform for IaC",
    "Pipelines (Azure DevOps / GitHub)",
    "Cost Management + budgets",
    "Ship an app to App Service + Azure SQL",
  ],
  Cloudflare: [
    "DNS + proxy basics",
    "Workers + bindings",
    "KV + R2 + D1 storage",
    "Durable Objects basics",
    "Pages deployments",
    "Cache rules + page rules",
    "WAF + rate limiting",
    "Tunnel + Access (Zero Trust)",
    "Workers Queues + Cron Triggers",
    "Wrangler CLI + local dev",
    "Observability + Logpush",
    "Ship an edge API on Workers",
  ],
  Vercel: [
    "Project setup + Git integration",
    "Environment variables (preview/prod)",
    "Serverless + edge functions",
    "Image + ISR + streaming",
    "Custom domains + SSL",
    "Analytics + Speed Insights",
    "Cron jobs + queues",
    "Logs + observability",
    "Preview deployments per PR",
    "Edge Config + KV (Marketplace)",
    "Vercel CLI + Build Output API",
    "Ship a production Vercel app",
  ],
  Heroku: [
    "Dyno model + scaling",
    "Add-ons (Postgres, Redis)",
    "Procfile + buildpacks",
    "Config vars + 12-factor",
    "Release phase + Pipelines",
    "Review apps + staging",
    "Logs + metrics + Logplex",
    "Backups + Postgres maintenance",
    "Heroku CI",
    "Containers via Container Registry",
    "Ship an app to Heroku production",
  ],

  // ─── DevOps ────────────────────────────────────────────────────────
  Docker: [
    "Run + manage containers",
    "Write a Dockerfile",
    "Layer caching + .dockerignore",
    "Volumes + networks",
    "Multi-stage builds",
    "docker-compose multi-service",
    "BuildKit + buildx (multi-arch)",
    "Push image to registry (GHCR / ECR)",
    "Image size + trivy security scan",
    "Healthchecks + restart policies",
    "Run as non-root + drop capabilities",
    "Ship a containerized service to prod",
  ],
  Kubernetes: [
    "Pods, ReplicaSets, Deployments",
    "Services (ClusterIP/NodePort/LB)",
    "ConfigMaps + Secrets",
    "Ingress + TLS (cert-manager)",
    "kubectl essentials + kubectx/kubens",
    "Helm charts + values",
    "Liveness / readiness / startup probes",
    "Resource requests + limits + HPA",
    "RBAC + ServiceAccounts",
    "Persistent volumes + StorageClasses",
    "Observability (Prometheus + Loki)",
    "Ship a workload to a production cluster",
  ],
  Terraform: [
    "Providers + resources + data sources",
    "Variables + outputs + locals",
    "State + remote backends (S3 + lock)",
    "Modules + reuse + versioning",
    "Plan / apply / destroy workflow",
    "Workspaces vs separate state files",
    "Sensitive vars + Vault / SOPS",
    "Drift detection + import existing",
    "Policy as code (Sentinel / OPA)",
    "CI with terraform fmt + validate + tflint",
    "Atlantis / Terraform Cloud workflow",
    "Ship infra to prod via Terraform",
  ],
  Ansible: [
    "Inventory (static + dynamic)",
    "Playbooks + plays + tasks",
    "Handlers + notify",
    "Roles + Galaxy",
    "Variables + precedence",
    "Templates (Jinja2)",
    "Vault for secrets",
    "Idempotency + check mode",
    "Tags + limit + serial rollouts",
    "Molecule tests for roles",
    "CI runs of playbooks",
    "Ship config-managed servers to prod",
  ],
  Jenkins: [
    "Jobs + freestyle vs pipeline",
    "Jenkinsfile (declarative)",
    "Shared libraries",
    "Agents + nodes + labels",
    "Credentials + secret handling",
    "Multibranch pipelines",
    "Plugins ecosystem (and risks)",
    "Artifacts + archive + fingerprint",
    "Blue Ocean view",
    "Backups + JCasC config-as-code",
    "Hardening + RBAC",
    "Ship a Jenkins-driven CD pipeline",
  ],
  "GitHub Actions": [
    "Workflow YAML + triggers",
    "Jobs + steps + matrix",
    "Reusable workflows + composite actions",
    "Secrets + environments + protection rules",
    "Caching + artifacts",
    "Self-hosted runners",
    "OIDC for cloud auth (no long-lived keys)",
    "Concurrency + cancel-in-progress",
    "Release automation + Changesets",
    "Security: pin SHAs + minimal perms",
    "Custom action (JS or Docker)",
    "Ship CI/CD for a real repo via Actions",
  ],
  "GitLab CI": [
    ".gitlab-ci.yml + stages + needs",
    "Runners (shared vs project)",
    "Variables + masked secrets",
    "Cache + artifacts",
    "Parent-child + multi-project pipelines",
    "Review apps + environments",
    "Auto DevOps overview",
    "Container scanning + SAST/DAST",
    "Deploy keys + protected branches",
    "OIDC to cloud providers",
    "Merge trains",
    "Ship a GitLab CI pipeline to prod",
  ],
  Linux: [
    "Filesystem + permissions + ACLs",
    "Process + signals + jobs",
    "Package managers (apt, dnf, pacman)",
    "systemd units + journal",
    "Networking (ip, ss, nc, tcpdump)",
    "Shell scripting fundamentals",
    "User + group management + sudoers",
    "SSH + keys + agent forwarding",
    "Cron / systemd timers",
    "Performance basics (top, htop, iostat)",
    "Hardening + firewalls (ufw / nftables)",
    "Ship + maintain a Linux server in prod",
  ],
  Nginx: [
    "server + location blocks",
    "Reverse proxy basics",
    "TLS + certbot + HTTP/2 + HTTP/3",
    "Rate limiting + connection limits",
    "Caching (proxy_cache)",
    "Load balancing upstreams + health checks",
    "WebSocket proxying",
    "Gzip + brotli compression",
    "Static file serving + try_files",
    "Logging + log_format",
    "Hardening (headers, hidden files)",
    "Ship Nginx in front of a production app",
  ],
  "CI/CD": [
    "Build pipeline anatomy",
    "Lint + test + build stages",
    "Artifacts + caching",
    "Environments + approvals",
    "Trunk-based vs GitFlow trade-offs",
    "Semantic versioning + changelogs",
    "Container image scanning",
    "Blue-green / canary deploys",
    "Database migration safety",
    "Rollback strategy + feature flags",
    "Observability tied to releases",
    "Ship a full CI/CD pipeline to prod",
  ],

  // ─── Data / AI ─────────────────────────────────────────────────────
  Pandas: [
    "Series + DataFrame basics",
    "Indexing (loc / iloc / boolean)",
    "GroupBy + aggregation",
    "Merge + join + concat",
    "Pivot / melt / wide vs long",
    "Time series (resample, rolling)",
    "Read/write CSV, Parquet, SQL",
    "Avoid SettingWithCopy + chained indexing",
    "Categoricals + memory usage",
    "Vectorize (no .iterrows()) + apply",
    "Profile with %timeit / line_profiler",
    "Ship an EDA notebook + report",
  ],
  NumPy: [
    "ndarray + dtypes",
    "Broadcasting rules",
    "Indexing + slicing + fancy indexing",
    "Vectorized ops vs Python loops",
    "Reductions + axis semantics",
    "Linear algebra (np.linalg)",
    "Random (np.random.Generator)",
    "Structured + record arrays",
    "Memory layout + views vs copies",
    "Profile + replace Python hotspots",
    "Interop with pandas / torch / tf",
    "Ship a numpy-backed numerical tool",
  ],
  Spark: [
    "RDD vs DataFrame vs Dataset",
    "Transformations vs actions (lazy eval)",
    "Partitioning + shuffle cost",
    "Spark SQL + UDFs (avoid Python UDFs)",
    "Catalyst optimizer basics",
    "Structured Streaming",
    "Delta Lake / Iceberg basics",
    "Caching + persist levels",
    "Skew + salting techniques",
    "Cluster sizing + executor tuning",
    "Spark UI to debug stages",
    "Ship a Spark ETL job in prod",
  ],
  Kafka: [
    "Topics, partitions, offsets",
    "Producers (acks, idempotence)",
    "Consumers + consumer groups",
    "Exactly-once semantics",
    "Schema Registry + Avro/Proto",
    "Compaction + retention policies",
    "Kafka Connect (source / sink)",
    "Kafka Streams or ksqlDB basics",
    "Monitoring (lag, ISR, throughput)",
    "Security (SASL/TLS + ACLs)",
    "Rebalancing + sticky assignor",
    "Ship an event pipeline to prod",
  ],
  Airflow: [
    "DAGs + tasks + operators",
    "Scheduling + catchup + backfills",
    "XCom for inter-task data",
    "Sensors + branching + trigger rules",
    "Connections + Hooks + Variables",
    "TaskFlow API (decorators)",
    "Dynamic task mapping",
    "Pools + slots + concurrency control",
    "KubernetesExecutor / CeleryExecutor",
    "Testing DAGs",
    "Monitoring + SLAs + alerts",
    "Ship a production-grade DAG",
  ],
  Snowflake: [
    "Warehouses + databases + schemas",
    "Roles + RBAC",
    "Loading data (COPY INTO / Snowpipe)",
    "Time Travel + zero-copy clones",
    "Tasks + Streams (CDC)",
    "Materialized views + result cache",
    "Resource monitors + cost control",
    "Secure views + row access policies",
    "Snowpark for Python",
    "Data sharing + Marketplace",
    "Query history + tuning",
    "Ship a Snowflake-backed pipeline",
  ],
  BigQuery: [
    "Datasets + tables + partitions + clustering",
    "Standard SQL features",
    "Slot model + on-demand vs reservation cost",
    "Scheduled queries + materialized views",
    "BigQuery ML basics",
    "External tables (BigLake / Iceberg)",
    "Authorized views + row-level security",
    "Streaming inserts + Storage Write API",
    "Query plan + execution stats tuning",
    "Avoid SELECT * + cost surprises",
    "Cloud Logging + audit logs",
    "Ship a BQ-backed analytics product",
  ],
  ETL: [
    "Extract / Transform / Load stages",
    "Idempotent + replayable pipelines",
    "Schema evolution strategy",
    "Backfills + late data handling",
    "Data quality tests (Great Expectations / dbt)",
    "Incremental vs full refresh",
    "Slowly Changing Dimensions (SCD)",
    "Orchestration (Airflow / Dagster / Prefect)",
    "Lineage + cataloging",
    "Cost + SLA monitoring",
    "PII + GDPR concerns + masking",
    "Ship an ELT/ETL pipeline to prod",
  ],
  TensorFlow: [
    "Tensors + variables",
    "tf.data input pipelines",
    "Keras Sequential + Functional + Subclass",
    "Custom layers + losses + metrics",
    "Callbacks (EarlyStopping, ModelCheckpoint)",
    "Custom training loop with tf.GradientTape",
    "Mixed precision + multi-GPU",
    "SavedModel + TF Serving / TFLite",
    "TensorBoard for tracking",
    "tf.function + autograph gotchas",
    "Profile with the TF Profiler",
    "Ship a TF model to production",
  ],
  PyTorch: [
    "Tensors + autograd",
    "nn.Module + optimizers + LR schedulers",
    "DataLoader + Dataset + collate",
    "Training loop + checkpoints",
    "GPU + mixed precision (amp)",
    "Distributed: DDP basics",
    "Transfer learning + fine-tuning",
    "TorchScript / torch.compile",
    "Profiler + Tensorboard",
    "Reproducibility (seeds + determinism)",
    "Serve via TorchServe / FastAPI",
    "Ship a PyTorch model to production",
  ],
  "scikit-learn": [
    "Estimator API (fit/predict/transform)",
    "Pipelines + ColumnTransformer",
    "Train/test split + leakage avoidance",
    "Cross-validation + GridSearchCV / Optuna",
    "Metrics + scoring + class imbalance",
    "Feature engineering + scaling",
    "Tree ensembles (RF / GBM) + early stopping",
    "Calibration + probability outputs",
    "Persistence (joblib) + versioning",
    "Pipeline + FastAPI service",
    "Monitor drift + retrain trigger",
    "Ship a sklearn model to production",
  ],
  LangChain: [
    "LLM + Chat model wrappers",
    "Prompt templates + LCEL",
    "Output parsers + structured output",
    "Retrievers + vector stores (Chroma/PGVector)",
    "RAG pipeline end-to-end",
    "Agents + tools + tool calling",
    "LangGraph for stateful workflows",
    "Streaming responses",
    "Tracing with LangSmith",
    "Evals + golden sets",
    "Caching + cost control",
    "Ship a LangChain app to production",
  ],
  "Machine Learning": [
    "Supervised vs unsupervised",
    "Train/val/test split + leakage",
    "Bias / variance + cross-validation",
    "Feature engineering + encoding",
    "Classification metrics (P/R/F1, ROC, PR)",
    "Regression metrics (RMSE, MAE, R²)",
    "Regularization (L1, L2) + elastic net",
    "Imbalanced data techniques",
    "Hyperparameter tuning (grid / Optuna)",
    "Model interpretability (SHAP)",
    "Drift + monitoring in production",
    "Ship one end-to-end ML project",
  ],
  "Deep Learning": [
    "Neural net fundamentals + backprop",
    "Optimizers (SGD, Adam, AdamW)",
    "CNNs for vision tasks",
    "RNNs + LSTMs (legacy but useful)",
    "Transformers + attention",
    "Regularization (dropout, weight decay, batchnorm)",
    "Transfer learning + fine-tuning",
    "Mixed precision + checkpointing",
    "Distributed training (DDP / FSDP) basics",
    "Quantization + pruning for inference",
    "Serving (Triton / Torch Serve)",
    "Train + ship a real DL model",
  ],
  NLP: [
    "Tokenization + subwords (BPE, WordPiece)",
    "Embeddings (word2vec → contextual)",
    "Bag-of-words + TF-IDF baselines",
    "Sequence models (RNN → Transformer)",
    "Attention + self-attention",
    "Fine-tune a Hugging Face model",
    "Evaluation (BLEU, ROUGE, F1, accuracy)",
    "Prompt engineering for LLMs",
    "RAG retrieval + reranking",
    "Vector DBs (PGVector, Qdrant)",
    "Safety + bias + hallucination mitigation",
    "Ship an NLP feature to production",
  ],

  // ─── Mobile ────────────────────────────────────────────────────────
  "React Native": [
    "Components + Flexbox layout",
    "Navigation (React Navigation)",
    "State + data fetching (TanStack Query)",
    "Native modules basics",
    "Expo workflow + EAS Build/Submit",
    "Push notifications",
    "Offline support + AsyncStorage / MMKV",
    "Animations (Reanimated)",
    "Platform-specific code + safe area",
    "Crash reporting + analytics",
    "Performance (Hermes, list virtualization)",
    "Ship an RN app to App Store + Play",
  ],
  Flutter: [
    "Widgets (Stateless + Stateful)",
    "Layout system + constraints",
    "Navigator 2.0 / go_router",
    "State mgmt (Provider, Riverpod, Bloc)",
    "Async + Future / Stream",
    "Networking + dio + json_serializable",
    "Local storage (Hive, Isar, drift)",
    "Platform channels for native APIs",
    "Flavors + env config",
    "Testing (unit, widget, integration)",
    "Performance (DevTools, repaint tracking)",
    "Ship a Flutter app to App Store + Play",
  ],
  Android: [
    "Activities + Fragments OR full Compose",
    "Jetpack Compose UI basics",
    "ViewModel + StateFlow + UI state",
    "Navigation Compose",
    "Room database + migrations",
    "Retrofit + OkHttp + interceptors",
    "WorkManager + background work",
    "Hilt / Dagger DI",
    "Coroutines + structured concurrency",
    "Permissions + lifecycle gotchas",
    "Crashlytics + Play Console internal testing",
    "Ship an Android app to Play Store",
  ],

  // ─── Tools / methodology ───────────────────────────────────────────
  Git: [
    "init, add, commit, log, diff",
    "Branching + merging",
    "Remote: clone, fetch, push, pull",
    "Rebase + interactive rebase",
    "Resolve merge conflicts",
    "Stash + cherry-pick",
    "Reflog + recover lost commits",
    "Bisect to find a bad commit",
    "Hooks (pre-commit / pre-push)",
    "Submodules vs subtrees vs sparse checkout",
    "PR workflow + signed commits",
    "Adopt a clean git workflow on a real repo",
  ],
  GitHub: [
    "Repos + issues + PRs",
    "Code review workflow",
    "Branch protection + CODEOWNERS",
    "Actions for CI",
    "Releases + tags + Changesets",
    "Projects + milestones",
    "Discussions + Wiki + Pages",
    "Dependabot + security advisories",
    "GitHub Apps + Personal Access Tokens",
    "Codespaces for cloud dev",
    "GitHub Packages registry",
    "Ship an open-source repo with full CI",
  ],
  GitLab: [
    "Repos + MRs",
    "CI/CD pipelines",
    "Issue boards + milestones",
    "Code owners + approval rules",
    "Container + package registry",
    "Environments + deploy boards",
    "Auto DevOps overview",
    "Secret detection + SAST",
    "GitLab Pages",
    "Self-hosted runners",
    "Use GitLab handbook patterns",
    "Ship a project from MR to prod via GitLab",
  ],
  Jira: [
    "Issues + epics + sprints",
    "Boards (Scrum / Kanban)",
    "Workflows + statuses",
    "JQL search",
    "Components + labels + versions",
    "Estimates + velocity reports",
    "Automations (rules)",
    "Linking issues + Smart Commits",
    "Integration with Git + CI",
    "Dashboards + filters",
    "Run a sprint cycle on a real project",
  ],
  Figma: [
    "Frames + auto layout",
    "Components + variants + properties",
    "Constraints + responsive design",
    "Styles + tokens",
    "Prototyping + interactions",
    "Variables + theme switching",
    "Dev mode + handoff",
    "Plugins (Tokens Studio, Iconify)",
    "Multi-page design systems",
    "Branching + version history",
    "Collaboration + comments",
    "Ship a design system used in a real product",
  ],
  Agile: [
    "Manifesto + 12 principles",
    "Iteration mindset",
    "Working software over docs",
    "Estimation pitfalls + #NoEstimates",
    "Continuous improvement",
    "Retrospectives that change something",
    "WIP limits + flow over utilization",
    "Customer collaboration patterns",
    "Roadmaps vs commitments",
    "Run a 2-week iteration on a real project",
  ],
  Scrum: [
    "Roles (PO, SM, Dev)",
    "Events (sprint, daily, review, retro)",
    "Artifacts (backlog, sprint backlog, increment)",
    "Definition of Ready / Done",
    "Story points + planning poker",
    "Refinement / grooming sessions",
    "Velocity + burndown reading",
    "Scaling patterns (LeSS, Nexus, SAFe overview)",
    "Coach a team through 1 sprint",
  ],
  TDD: [
    "Red → Green → Refactor",
    "Arrange / Act / Assert",
    "Test doubles (mock, stub, fake, spy)",
    "Outside-in vs inside-out style",
    "Coverage vs quality",
    "Mutation testing intro",
    "Property-based testing intro",
    "Test naming + readability",
    "Refactor with confidence",
    "Pair on a TDD kata (Bowling / Roman Numerals)",
    "Add TDD discipline to a real project",
  ],
  Microservices: [
    "Service boundaries + bounded contexts",
    "Sync vs async communication trade-offs",
    "Service discovery + load balancing",
    "API gateway pattern",
    "Saga + outbox patterns",
    "Idempotency + retries + circuit breakers",
    "Versioning + backward compatibility",
    "Observability (logs, metrics, traces)",
    "Schema evolution across services",
    "Data ownership + no shared DB",
    "Deploy + roll back independently",
    "Ship a 2+ service system to production",
  ],

  // ─── Extras (used elsewhere in app) ────────────────────────────────
  Communication: [
    "Write a clear PR description",
    "Document architectural decisions (ADRs)",
    "Async-first updates",
    "Diagrams (sequence, C4, ER)",
    "Run a useful standup / status update",
    "Write a postmortem without blame",
    "Lead a design review meeting",
    "Explain a tradeoff to non-engineers",
  ],
  "Problem Solving": [
    "Arrays + strings",
    "Hash maps + sets",
    "Two pointers + sliding window",
    "Binary search variants",
    "Trees + graph traversal (BFS/DFS)",
    "Heap + priority queue patterns",
    "Backtracking",
    "Dynamic programming basics",
    "Greedy vs DP intuition",
    "System design fundamentals",
    "Mock interviews + post-mortems",
    "Solve 1 medium per day for a month",
  ],
};

export function useSkillMilestones(skill: string) {
  const data = useQuery(api.milestones.listBySkill, { skill });
  const seedIfEmpty = useMutation(api.milestones.seedIfEmpty);
  const addMut = useMutation(api.milestones.add);
  const toggleMut = useMutation(api.milestones.toggle);
  const updateTextMut = useMutation(api.milestones.updateText);
  const removeMut = useMutation(api.milestones.remove);
  const replaceForSkill = useMutation(api.milestones.replaceForSkill);

  useEffect(() => {
    if (data === undefined) return;
    if (data.length > 0) return;
    const preset = DEFAULT_MILESTONES[skill];
    if (!preset || preset.length === 0) return;
    seedIfEmpty({ skill, texts: preset }).catch(() => {});
  }, [data, skill, seedIfEmpty]);

  const items: Milestone[] = (data ?? []).map((r) => ({
    _id: r._id,
    text: r.text,
    done: r.done,
    order: r.order,
  }));

  const add = useCallback(
    (text: string) => {
      if (!text.trim()) return;
      void addMut({ skill, text });
    },
    [addMut, skill],
  );

  const toggle = useCallback(
    (id: Id<"milestones">) => {
      void toggleMut({ id });
    },
    [toggleMut],
  );

  const updateText = useCallback(
    (id: Id<"milestones">, text: string) => {
      void updateTextMut({ id, text });
    },
    [updateTextMut],
  );

  const remove = useCallback(
    (id: Id<"milestones">) => {
      void removeMut({ id });
    },
    [removeMut],
  );

  const reset = useCallback(() => {
    const preset = DEFAULT_MILESTONES[skill] ?? [];
    void replaceForSkill({ skill, texts: preset });
  }, [replaceForSkill, skill]);

  const ready = data !== undefined;
  const progress = items.length === 0 ? 0 : items.filter((m) => m.done).length / items.length;

  return { items, ready, add, toggle, updateText, remove, reset, progress };
}
