// Curated free learning resources per skill. 100% free only.
// YouTube links are real playlists from verified channels (Bro Code, The Net
// Ninja, freeCodeCamp, Programming with Mosh, Corey Schafer, Hussein Nasser,
// TechWorld with Nana, Kevin Powell, Traversy Media, Confluent, etc.).
// Per-skill minimum: 1 official docs + 1 long-form reading + 1 YouTube
// playlist + 1 hands-on project + 1 more.

export type Resource = { title: string; url: string; kind: "docs" | "course" | "video" | "book" | "project" };

export const RESOURCES: Record<string, Resource[]> = {
  // ─── Languages ──────────────────────────────────────────────────────
  Python: [
    { title: "Python official tutorial", url: "https://docs.python.org/3/tutorial/", kind: "docs" },
    { title: "Real Python — beginner path", url: "https://realpython.com/learning-paths/python-basics/", kind: "course" },
    { title: "Automate the Boring Stuff (book)", url: "https://automatetheboringstuff.com/", kind: "book" },
    { title: "Bro Code — Python tutorial playlist", url: "https://www.youtube.com/playlist?list=PLZPZq0r_RZOOkUQbat8LyQii36cJf2SWT", kind: "video" },
    { title: "Programming with Mosh — Python playlist", url: "https://www.youtube.com/playlist?list=PLdOkxMYZtDaJJJNS0I5mqkCAXBFXPMyWh", kind: "video" },
    { title: "Build: CLI scraper or REST API", url: "/jobs?skill=Python", kind: "project" },
  ],
  JavaScript: [
    { title: "MDN — JavaScript guide", url: "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide", kind: "docs" },
    { title: "javascript.info — Modern JS Tutorial", url: "https://javascript.info/", kind: "course" },
    { title: "Eloquent JavaScript (free book)", url: "https://eloquentjavascript.net/", kind: "book" },
    { title: "The Net Ninja — Modern JavaScript playlist", url: "https://www.youtube.com/playlist?list=PLqyUgadpThTIh8UiNG0F8f46QVSRL_K8L", kind: "video" },
    { title: "Bro Code — JavaScript playlist", url: "https://www.youtube.com/playlist?list=PLZPZq0r_RZOO1zkgO4bIdfuLpizCeHYKv", kind: "video" },
    { title: "Build: SPA without a framework", url: "/jobs?skill=JavaScript", kind: "project" },
  ],
  TypeScript: [
    { title: "TS Handbook", url: "https://www.typescriptlang.org/docs/handbook/intro.html", kind: "docs" },
    { title: "Total TypeScript Beginners (free)", url: "https://www.totaltypescript.com/tutorials", kind: "course" },
    { title: "The Net Ninja — TypeScript playlist", url: "https://www.youtube.com/playlist?list=PL4cUxeGkcC9gUgr39Q_yD6v-bSyMwKPUI", kind: "video" },
    { title: "type-challenges practice", url: "https://github.com/type-challenges/type-challenges", kind: "project" },
    { title: "Effective TypeScript (free articles)", url: "https://effectivetypescript.com/", kind: "book" },
    { title: "Convert a JS app to strict TS", url: "/jobs?skill=TypeScript", kind: "project" },
  ],
  Java: [
    { title: "Oracle Java Tutorials", url: "https://docs.oracle.com/javase/tutorial/", kind: "docs" },
    { title: "Baeldung — Java guides", url: "https://www.baeldung.com/start-here", kind: "book" },
    { title: "Bro Code — Java playlist", url: "https://www.youtube.com/playlist?list=PLZPZq0r_RZOOj_NOZYq_R2PECIMglLemc", kind: "video" },
    { title: "freeCodeCamp — Java for beginners (8h)", url: "https://www.youtube.com/watch?v=A74TOX803D0", kind: "video" },
    { title: "Build: Spring Boot REST API", url: "/jobs?skill=Java", kind: "project" },
  ],
  "C++": [
    { title: "learncpp.com (free, comprehensive)", url: "https://www.learncpp.com/", kind: "book" },
    { title: "cppreference.com", url: "https://en.cppreference.com/w/", kind: "docs" },
    { title: "Bro Code — C++ playlist", url: "https://www.youtube.com/playlist?list=PLZPZq0r_RZOMHoXIcxze_lP97j2Ase2on", kind: "video" },
    { title: "The Cherno — C++ series playlist", url: "https://www.youtube.com/playlist?list=PLlrATfBNZ98dudnM48yfGUldqGD0S4FFb", kind: "video" },
    { title: "Build: small game with raylib", url: "/jobs?skill=C%2B%2B", kind: "project" },
  ],
  "C#": [
    { title: "Microsoft Learn — C# path", url: "https://learn.microsoft.com/en-us/training/paths/csharp-first-steps/", kind: "course" },
    { title: "C# docs", url: "https://learn.microsoft.com/en-us/dotnet/csharp/", kind: "docs" },
    { title: "Bro Code — C# playlist", url: "https://www.youtube.com/playlist?list=PLZPZq0r_RZOPNy28FDBys3GVP2LiaIyP_", kind: "video" },
    { title: "Tim Corey — C# Mastercourse playlist", url: "https://www.youtube.com/@IAmTimCorey/playlists", kind: "video" },
    { title: "Build: ASP.NET Core Web API", url: "/jobs?skill=C%23", kind: "project" },
  ],
  Go: [
    { title: "A Tour of Go", url: "https://go.dev/tour/welcome/1", kind: "course" },
    { title: "Effective Go", url: "https://go.dev/doc/effective_go", kind: "docs" },
    { title: "Go by Example", url: "https://gobyexample.com/", kind: "docs" },
    { title: "Learn Go with Tests (free book)", url: "https://quii.gitbook.io/learn-go-with-tests", kind: "book" },
    { title: "freeCodeCamp — Go Programming course", url: "https://www.youtube.com/watch?v=un6ZyFkqFKo", kind: "video" },
    { title: "Build: HTTP service with net/http", url: "/jobs?skill=Go", kind: "project" },
  ],
  Rust: [
    { title: "The Rust Book (free)", url: "https://doc.rust-lang.org/book/", kind: "book" },
    { title: "Rustlings exercises", url: "https://github.com/rust-lang/rustlings", kind: "course" },
    { title: "Rust by Example", url: "https://doc.rust-lang.org/rust-by-example/", kind: "docs" },
    { title: "freeCodeCamp — Learn Rust Programming (14h)", url: "https://www.youtube.com/watch?v=BpPEoZW5IiY", kind: "video" },
    { title: "Build: CLI tool with clap", url: "/jobs?skill=Rust", kind: "project" },
  ],
  Ruby: [
    { title: "Ruby docs", url: "https://ruby-doc.org/", kind: "docs" },
    { title: "The Odin Project — Ruby path", url: "https://www.theodinproject.com/paths/full-stack-ruby-on-rails/courses/ruby", kind: "course" },
    { title: "Learn Ruby the Hard Way (free online)", url: "https://learnrubythehardway.org/book/", kind: "book" },
    { title: "GoRails — free episodes", url: "https://gorails.com/episodes?free=true", kind: "video" },
    { title: "Drifting Ruby — playlists", url: "https://www.youtube.com/@DriftingRuby/playlists", kind: "video" },
    { title: "Build: Rails or Sinatra app", url: "/jobs?skill=Ruby", kind: "project" },
  ],
  PHP: [
    { title: "PHP — The Right Way", url: "https://phptherightway.com/", kind: "book" },
    { title: "PHP official manual", url: "https://www.php.net/manual/en/", kind: "docs" },
    { title: "Laracasts — PHP for Beginners (free)", url: "https://laracasts.com/series/php-for-beginners-2023-edition", kind: "course" },
    { title: "Traversy Media — PHP Front to Back playlist", url: "https://www.youtube.com/playlist?list=PLillGF-Rfqbap2IB6ZS4BBBcYPagAjpjn", kind: "video" },
    { title: "The Net Ninja — PHP & MySQL playlist", url: "https://www.youtube.com/playlist?list=PL4cUxeGkcC9gksOX3Kd9KPo-O68ncT05o", kind: "video" },
    { title: "Build: small CMS or REST API", url: "/jobs?skill=PHP", kind: "project" },
  ],
  Kotlin: [
    { title: "Kotlin docs", url: "https://kotlinlang.org/docs/home.html", kind: "docs" },
    { title: "Kotlin Koans (interactive)", url: "https://kotlinlang.org/docs/koans.html", kind: "course" },
    { title: "JetBrains Hyperskill — Kotlin free track", url: "https://hyperskill.org/", kind: "course" },
    { title: "Bro Code — Kotlin for Android playlist", url: "https://www.youtube.com/playlist?list=PLlxmoA0rQ-LwgK1JsnMsakYNACYGa1cjR", kind: "video" },
    { title: "Philipp Lackner — Android+Kotlin playlists", url: "https://www.youtube.com/@PhilippLackner/playlists", kind: "video" },
    { title: "Build: Android app or Ktor service", url: "/jobs?skill=Kotlin", kind: "project" },
  ],
  Swift: [
    { title: "Swift docs", url: "https://www.swift.org/documentation/", kind: "docs" },
    { title: "100 Days of SwiftUI (Hacking with Swift, free)", url: "https://www.hackingwithswift.com/100/swiftui", kind: "course" },
    { title: "Stanford CS193p — iOS Dev", url: "https://cs193p.sites.stanford.edu/", kind: "course" },
    { title: "Sean Allen — Swift playlists", url: "https://www.youtube.com/@SeanAllen/playlists", kind: "video" },
    { title: "Build: small iOS app", url: "/jobs?skill=Swift", kind: "project" },
  ],
  Scala: [
    { title: "Scala 3 Book (free)", url: "https://docs.scala-lang.org/scala3/book/introduction.html", kind: "book" },
    { title: "Scala docs", url: "https://docs.scala-lang.org/", kind: "docs" },
    { title: "Hands-On Scala (Li Haoyi, free online)", url: "https://www.handsonscala.com/", kind: "book" },
    { title: "Rock the JVM — free playlists", url: "https://www.youtube.com/@rockthejvm/playlists", kind: "video" },
    { title: "Build: small functional app", url: "/jobs?skill=Scala", kind: "project" },
  ],
  SQL: [
    { title: "SQLBolt — interactive lessons", url: "https://sqlbolt.com/", kind: "course" },
    { title: "PostgreSQL Tutorial", url: "https://www.postgresqltutorial.com/", kind: "docs" },
    { title: "Use The Index, Luke (free book)", url: "https://use-the-index-luke.com/", kind: "book" },
    { title: "Programming with Mosh — Complete SQL Mastery playlist", url: "https://www.youtube.com/playlist?list=PLOghUv2IDLKHKlkQNuzN8SPLYuVhhLlpa", kind: "video" },
    { title: "Bro Code — MySQL playlist", url: "https://www.youtube.com/playlist?list=PLZPZq0r_RZOMskz6MdsMOgxzheIyjo-BZ", kind: "video" },
    { title: "Practice: PostgreSQL Exercises", url: "https://pgexercises.com/", kind: "project" },
  ],
  Bash: [
    { title: "Bash Guide for Beginners", url: "https://tldp.org/LDP/Bash-Beginners-Guide/html/", kind: "book" },
    { title: "GNU Bash reference manual", url: "https://www.gnu.org/software/bash/manual/bash.html", kind: "docs" },
    { title: "ShellCheck (online linter)", url: "https://www.shellcheck.net/", kind: "project" },
    { title: "Joe Collins — Linux Command Line playlist", url: "https://www.youtube.com/playlist?list=PLS1QulWo1RIb9WVQGJ_vh-RQusbZgO_As", kind: "video" },
    { title: "ExplainShell (interactive)", url: "https://explainshell.com/", kind: "course" },
    { title: "Build: 1 useful sysadmin script", url: "/jobs?skill=Bash", kind: "project" },
  ],

  // ─── Backend frameworks ─────────────────────────────────────────────
  FastAPI: [
    { title: "FastAPI official tutorial", url: "https://fastapi.tiangolo.com/tutorial/", kind: "docs" },
    { title: "FastAPI advanced guide", url: "https://fastapi.tiangolo.com/advanced/", kind: "docs" },
    { title: "Real Python — FastAPI guide", url: "https://realpython.com/fastapi-python-web-apis/", kind: "book" },
    { title: "freeCodeCamp — FastAPI full course (19h)", url: "https://www.youtube.com/watch?v=0sOvCWFmrtA", kind: "video" },
    { title: "freeCodeCamp — FastAPI beginners course", url: "https://www.youtube.com/watch?v=tLKKmouUams", kind: "video" },
    { title: "Build: production API with auth + DB", url: "/jobs?skill=FastAPI", kind: "project" },
  ],
  Django: [
    { title: "Django docs tutorial", url: "https://docs.djangoproject.com/en/stable/intro/tutorial01/", kind: "docs" },
    { title: "Django for Beginners (free chapter)", url: "https://djangoforbeginners.com/", kind: "book" },
    { title: "Django REST Framework", url: "https://www.django-rest-framework.org/", kind: "docs" },
    { title: "Corey Schafer — Django series playlist", url: "https://www.youtube.com/playlist?list=PLLtIxaRk6P3JRiiW1SAV2BLhuuSSCULRn", kind: "video" },
    { title: "The Net Ninja — Django blog playlist", url: "https://www.youtube.com/playlist?list=PL4cUxeGkcC9iqfAag3a_BKEX1N43uJutw", kind: "video" },
    { title: "Build: blog + auth + admin", url: "/jobs?skill=Django", kind: "project" },
  ],
  Flask: [
    { title: "Flask docs", url: "https://flask.palletsprojects.com/", kind: "docs" },
    { title: "Flask Mega-Tutorial (Miguel Grinberg)", url: "https://blog.miguelgrinberg.com/post/the-flask-mega-tutorial-part-i-hello-world", kind: "book" },
    { title: "Corey Schafer — Flask playlist", url: "https://www.youtube.com/playlist?list=PL-osiE80TeTs4UjLw5MM6OjgkjFeUxCYH", kind: "video" },
    { title: "Real Python — Flask guides", url: "https://realpython.com/tutorials/flask/", kind: "course" },
    { title: "Build: REST API + Postgres + auth", url: "/jobs?skill=Flask", kind: "project" },
  ],
  "Node.js": [
    { title: "Node.js docs — Learn", url: "https://nodejs.org/en/learn", kind: "docs" },
    { title: "Node.js Design Patterns (free chapter)", url: "https://www.nodejsdesignpatterns.com/", kind: "book" },
    { title: "The Net Ninja — Node.js playlist", url: "https://www.youtube.com/playlist?list=PL4cUxeGkcC9gcy9lrvMJ75z9maRw4byYp", kind: "video" },
    { title: "freeCodeCamp — Node + Express course", url: "https://www.youtube.com/watch?v=Oe421EPjeBE", kind: "video" },
    { title: "Build: REST API with Express + Postgres", url: "/jobs?skill=Node.js", kind: "project" },
  ],
  Express: [
    { title: "Express docs", url: "https://expressjs.com/en/starter/installing.html", kind: "docs" },
    { title: "MDN — Express/Node tutorial", url: "https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs", kind: "course" },
    { title: "The Net Ninja — Node + Express playlist", url: "https://www.youtube.com/playlist?list=PL4cUxeGkcC9gcy9lrvMJ75z9maRw4byYp", kind: "video" },
    { title: "Express security best practices", url: "https://expressjs.com/en/advanced/best-practice-security.html", kind: "book" },
    { title: "Build: REST API with auth + Postgres", url: "/jobs?skill=Express", kind: "project" },
  ],
  NestJS: [
    { title: "NestJS docs", url: "https://docs.nestjs.com/", kind: "docs" },
    { title: "NestJS — official courses page", url: "https://courses.nestjs.com/", kind: "course" },
    { title: "Awesome Nest (curated)", url: "https://github.com/nestjs/awesome-nestjs", kind: "book" },
    { title: "freeCodeCamp — NestJS full course", url: "https://www.youtube.com/watch?v=GHTA143_b-s", kind: "video" },
    { title: "Build: microservice with Postgres + JWT", url: "/jobs?skill=NestJS", kind: "project" },
  ],
  Spring: [
    { title: "Spring Boot reference", url: "https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/", kind: "docs" },
    { title: "Spring guides", url: "https://spring.io/guides", kind: "course" },
    { title: "Baeldung — Spring", url: "https://www.baeldung.com/spring-tutorial", kind: "book" },
    { title: "Amigoscode — Spring & Spring Boot playlist", url: "https://www.youtube.com/playlist?list=PLwvrYc43l1MzeA2bBYQhCWr2gvWLs9A7S", kind: "video" },
    { title: "Build: REST API + Spring Data JPA", url: "/jobs?skill=Spring", kind: "project" },
  ],
  Rails: [
    { title: "Getting Started with Rails", url: "https://guides.rubyonrails.org/getting_started.html", kind: "docs" },
    { title: "Rails Guides", url: "https://guides.rubyonrails.org/", kind: "book" },
    { title: "GoRails — free episodes", url: "https://gorails.com/episodes?free=true", kind: "video" },
    { title: "Drifting Ruby — playlists", url: "https://www.youtube.com/@DriftingRuby/playlists", kind: "video" },
    { title: "Build: blog or SaaS MVP", url: "/jobs?skill=Rails", kind: "project" },
  ],
  Laravel: [
    { title: "Laravel docs", url: "https://laravel.com/docs", kind: "docs" },
    { title: "Laracasts — Laravel From Scratch (free)", url: "https://laracasts.com/series/30-days-to-learn-laravel-11", kind: "course" },
    { title: "The Net Ninja — Laravel for Beginners playlist", url: "https://www.youtube.com/playlist?list=PL4cUxeGkcC9hL6aCFKyagrT1RCfVN4w2Q", kind: "video" },
    { title: "Laravel Daily — Quick Tips playlist", url: "https://www.youtube.com/playlist?list=PLdXLsjL7A9k1yM3CT73ZIaKLXpywH-mGQ", kind: "video" },
    { title: "Laravel Bootcamp (free)", url: "https://bootcamp.laravel.com/", kind: "book" },
    { title: "Build: e-commerce or SaaS MVP", url: "/jobs?skill=Laravel", kind: "project" },
  ],
  "ASP.NET": [
    { title: "ASP.NET Core docs", url: "https://learn.microsoft.com/en-us/aspnet/core/", kind: "docs" },
    { title: "Microsoft Learn — Web API path", url: "https://learn.microsoft.com/en-us/training/paths/create-web-api-aspnet-core/", kind: "course" },
    { title: "Nick Chapsas — .NET playlists", url: "https://www.youtube.com/@nickchapsas/playlists", kind: "video" },
    { title: "Tim Corey — .NET tutorials", url: "https://www.youtube.com/@IAmTimCorey/playlists", kind: "video" },
    { title: "Build: minimal API + EF Core + JWT", url: "/jobs?skill=ASP.NET", kind: "project" },
  ],
  GraphQL: [
    { title: "How to GraphQL (free)", url: "https://www.howtographql.com/", kind: "course" },
    { title: "GraphQL official docs", url: "https://graphql.org/learn/", kind: "docs" },
    { title: "Apollo docs", url: "https://www.apollographql.com/docs/", kind: "book" },
    { title: "The Net Ninja — GraphQL playlist", url: "https://www.youtube.com/playlist?list=PL4cUxeGkcC9iK6Qhn-QLcXCXPQUov1U7f", kind: "video" },
    { title: "Build: GraphQL API on top of REST data", url: "/jobs?skill=GraphQL", kind: "project" },
  ],
  gRPC: [
    { title: "gRPC docs", url: "https://grpc.io/docs/", kind: "docs" },
    { title: "Protocol Buffers guide", url: "https://protobuf.dev/programming-guides/proto3/", kind: "book" },
    { title: "TechWorld with Nana — gRPC intro", url: "https://www.youtube.com/watch?v=hVrwuMnCtok", kind: "video" },
    { title: "Hussein Nasser — gRPC playlists", url: "https://www.youtube.com/@hnasr/playlists", kind: "video" },
    { title: "Build: polyglot service with streaming RPC", url: "/jobs?skill=gRPC", kind: "project" },
  ],
  REST: [
    { title: "RESTful web API design — Microsoft", url: "https://learn.microsoft.com/en-us/azure/architecture/best-practices/api-design", kind: "docs" },
    { title: "REST API Tutorial", url: "https://restfulapi.net/", kind: "course" },
    { title: "Roy Fielding's REST chapter", url: "https://www.ics.uci.edu/~fielding/pubs/dissertation/rest_arch_style.htm", kind: "book" },
    { title: "Hussein Nasser — APIs playlists", url: "https://www.youtube.com/@hnasr/playlists", kind: "video" },
    { title: "Build: well-versioned REST API with OpenAPI", url: "/jobs?skill=REST", kind: "project" },
  ],

  // ─── Frontend ───────────────────────────────────────────────────────
  React: [
    { title: "React docs", url: "https://react.dev/learn", kind: "docs" },
    { title: "Patterns.dev — React", url: "https://www.patterns.dev/react", kind: "book" },
    { title: "The Net Ninja — Full Modern React playlist", url: "https://www.youtube.com/playlist?list=PL4cUxeGkcC9gZD-Tvwfod2gaISzfRiP9d", kind: "video" },
    { title: "Programming with Mosh — React playlist", url: "https://www.youtube.com/playlist?list=PLz3Ag2iSYROv8RBG85oZA36sDQj3AmQj3", kind: "video" },
    { title: "Build: dashboard with React Query", url: "/jobs?skill=React", kind: "project" },
  ],
  "Next.js": [
    { title: "Next.js docs", url: "https://nextjs.org/docs", kind: "docs" },
    { title: "Next.js — Learn (interactive)", url: "https://nextjs.org/learn", kind: "course" },
    { title: "The Net Ninja — Next.js for Beginners playlist", url: "https://www.youtube.com/playlist?list=PL4cUxeGkcC9g9gP2onazU5-2M-AzA8eBw", kind: "video" },
    { title: "Lee Robinson — Next.js playlists", url: "https://www.youtube.com/@leerob/playlists", kind: "video" },
    { title: "Vercel templates", url: "https://vercel.com/templates", kind: "book" },
    { title: "Build: SaaS starter with auth + DB", url: "/jobs?skill=Next.js", kind: "project" },
  ],
  Vue: [
    { title: "Vue official tutorial", url: "https://vuejs.org/tutorial/", kind: "course" },
    { title: "Vue docs", url: "https://vuejs.org/guide/introduction.html", kind: "docs" },
    { title: "Vue Mastery — free intro", url: "https://www.vuemastery.com/courses/", kind: "book" },
    { title: "The Net Ninja — Vue.js 3 playlist", url: "https://www.youtube.com/playlist?list=PL4cUxeGkcC9hYYGbV60Vq3IXYNfDk8At1", kind: "video" },
    { title: "Build: SPA with Pinia + Vue Router", url: "/jobs?skill=Vue", kind: "project" },
  ],
  Nuxt: [
    { title: "Nuxt docs", url: "https://nuxt.com/docs", kind: "docs" },
    { title: "Nuxt examples", url: "https://nuxt.com/docs/examples", kind: "book" },
    { title: "LearnVue — Nuxt playlists", url: "https://www.youtube.com/@LearnVue/playlists", kind: "video" },
    { title: "The Net Ninja — Nuxt 3 content", url: "https://www.youtube.com/@NetNinja/playlists", kind: "video" },
    { title: "Build: full-stack Nuxt + Nitro app", url: "/jobs?skill=Nuxt", kind: "project" },
  ],
  Angular: [
    { title: "Angular docs", url: "https://angular.dev/overview", kind: "docs" },
    { title: "Angular Tour of Heroes", url: "https://angular.dev/tutorials/learn-angular", kind: "course" },
    { title: "Angular University — All Tutorials playlist", url: "https://www.youtube.com/playlist?list=PLOa5YIicjJ-WUG1CbYYr44yczxVQKRE0i", kind: "video" },
    { title: "Decoded Frontend — Angular playlists", url: "https://www.youtube.com/@DecodedFrontend/playlists", kind: "video" },
    { title: "Build: dashboard SPA with RxJS", url: "/jobs?skill=Angular", kind: "project" },
  ],
  Svelte: [
    { title: "Svelte tutorial", url: "https://learn.svelte.dev/", kind: "course" },
    { title: "Svelte + SvelteKit docs", url: "https://svelte.dev/docs", kind: "docs" },
    { title: "The Net Ninja — Svelte for Beginners playlist", url: "https://www.youtube.com/playlist?list=PL4cUxeGkcC9hlbrVO_2QFVqVPhlZmz7tO", kind: "video" },
    { title: "Joy of Code — Svelte playlists", url: "https://www.youtube.com/@JoyofCodeDev/playlists", kind: "video" },
    { title: "Build: SvelteKit blog or SaaS MVP", url: "/jobs?skill=Svelte", kind: "project" },
  ],
  HTML: [
    { title: "MDN — HTML basics", url: "https://developer.mozilla.org/en-US/docs/Learn/HTML", kind: "docs" },
    { title: "web.dev — Learn HTML", url: "https://web.dev/learn/html", kind: "course" },
    { title: "HTML Living Standard", url: "https://html.spec.whatwg.org/multipage/", kind: "book" },
    { title: "The Net Ninja — HTML for Beginners playlist", url: "https://www.youtube.com/playlist?list=PL4cUxeGkcC9ibZ2TSBaGGNrgh4ZgYE6Cc", kind: "video" },
    { title: "Bro Code — HTML & CSS playlist", url: "https://www.youtube.com/playlist?list=PLZPZq0r_RZOOxqHgOzPyCzIl4AJjXbCYt", kind: "video" },
    { title: "Practice: Frontend Mentor", url: "https://www.frontendmentor.io/", kind: "project" },
  ],
  CSS: [
    { title: "MDN — CSS basics", url: "https://developer.mozilla.org/en-US/docs/Learn/CSS", kind: "docs" },
    { title: "web.dev — Learn CSS", url: "https://web.dev/learn/css", kind: "course" },
    { title: "CSS Tricks — Flexbox guide", url: "https://css-tricks.com/snippets/css/a-guide-to-flexbox/", kind: "book" },
    { title: "The Net Ninja — CSS Tutorials for Beginners playlist", url: "https://www.youtube.com/playlist?list=PL4cUxeGkcC9gQeDH6xYhmO-db2mhoTSrT", kind: "video" },
    { title: "Kevin Powell — Flexbox playlist", url: "https://www.youtube.com/playlist?list=PL6bZHMk2QK-Umsq581EkJiU1qpRef-QxP", kind: "video" },
    { title: "Practice: Frontend Mentor", url: "https://www.frontendmentor.io/", kind: "project" },
  ],
  Tailwind: [
    { title: "Tailwind docs", url: "https://tailwindcss.com/docs/installation", kind: "docs" },
    { title: "The Net Ninja — Tailwind CSS playlist", url: "https://www.youtube.com/playlist?list=PL4cUxeGkcC9gpXORlEHjc5bgnIi5HEGhw", kind: "video" },
    { title: "Tailwind Labs — official playlists", url: "https://www.youtube.com/@TailwindLabs/playlists", kind: "video" },
    { title: "Refactoring UI — free articles", url: "https://www.refactoringui.com/", kind: "book" },
    { title: "Headless UI examples", url: "https://headlessui.com/", kind: "project" },
    { title: "Build: rebuild a SaaS dashboard layout", url: "/jobs?skill=Tailwind", kind: "project" },
  ],
  Sass: [
    { title: "Sass docs", url: "https://sass-lang.com/documentation/", kind: "docs" },
    { title: "Sass guidelines", url: "https://sass-guidelin.es/", kind: "book" },
    { title: "The Net Ninja — SASS Tutorial playlist", url: "https://www.youtube.com/playlist?list=PL4cUxeGkcC9iEwigam3gTjU_7IA3W2WZA", kind: "video" },
    { title: "Kevin Powell — playlists", url: "https://www.youtube.com/@KevinPowell/playlists", kind: "video" },
    { title: "Build: refactor a CSS project to SCSS", url: "/jobs?skill=Sass", kind: "project" },
  ],
  Redux: [
    { title: "Redux Toolkit Essentials", url: "https://redux.js.org/tutorials/essentials/part-1-overview-concepts", kind: "docs" },
    { title: "Redux Style Guide", url: "https://redux.js.org/style-guide/", kind: "book" },
    { title: "The Net Ninja — Complete React with Redux playlist", url: "https://www.youtube.com/playlist?list=PL4cUxeGkcC9ij8CfkAY2RAGb-tmkNwQHG", kind: "video" },
    { title: "Mark Erikson — blog (Redux maintainer)", url: "https://blog.isquaredsoftware.com/", kind: "course" },
    { title: "Build: app with RTK Query", url: "/jobs?skill=Redux", kind: "project" },
  ],
  Vite: [
    { title: "Vite docs", url: "https://vitejs.dev/guide/", kind: "docs" },
    { title: "Vite plugin guide", url: "https://vitejs.dev/guide/api-plugin", kind: "book" },
    { title: "Fireship — Vite in 100s", url: "https://www.youtube.com/watch?v=KCrXgy8qtjM", kind: "video" },
    { title: "Awesome Vite (curated)", url: "https://github.com/vitejs/awesome-vite", kind: "course" },
    { title: "Build: migrate a CRA app to Vite", url: "/jobs?skill=Vite", kind: "project" },
  ],
  Webpack: [
    { title: "Webpack — Getting Started", url: "https://webpack.js.org/guides/getting-started/", kind: "docs" },
    { title: "SurviveJS — Webpack (free book)", url: "https://survivejs.com/webpack/foreword/", kind: "book" },
    { title: "Colt Steele — Webpack overview", url: "https://www.youtube.com/watch?v=IkdmHk4MMcc", kind: "video" },
    { title: "Webpack concepts deep dive", url: "https://webpack.js.org/concepts/", kind: "course" },
    { title: "Build: custom Webpack config for a React app", url: "/jobs?skill=Webpack", kind: "project" },
  ],

  // ─── Databases ──────────────────────────────────────────────────────
  PostgreSQL: [
    { title: "PostgreSQL docs", url: "https://www.postgresql.org/docs/current/", kind: "docs" },
    { title: "PostgreSQL Tutorial", url: "https://www.postgresqltutorial.com/", kind: "book" },
    { title: "Use The Index, Luke (free book)", url: "https://use-the-index-luke.com/", kind: "book" },
    { title: "Hussein Nasser — PostgreSQL playlist", url: "https://www.youtube.com/playlist?list=PLQnljOFTspQWGrOqslniFlRcwxyY94cjj", kind: "video" },
    { title: "Practice: PostgreSQL Exercises", url: "https://pgexercises.com/", kind: "project" },
  ],
  MySQL: [
    { title: "MySQL docs", url: "https://dev.mysql.com/doc/", kind: "docs" },
    { title: "MySQL Tutorial", url: "https://www.mysqltutorial.org/", kind: "book" },
    { title: "Bro Code — MySQL playlist", url: "https://www.youtube.com/playlist?list=PLZPZq0r_RZOMskz6MdsMOgxzheIyjo-BZ", kind: "video" },
    { title: "Practice: SQLZoo", url: "https://sqlzoo.net/", kind: "project" },
    { title: "Build: MySQL-backed app + tuned indexes", url: "/jobs?skill=MySQL", kind: "project" },
  ],
  SQLite: [
    { title: "SQLite docs", url: "https://www.sqlite.org/docs.html", kind: "docs" },
    { title: "SQLite Tutorial", url: "https://www.sqlitetutorial.net/", kind: "book" },
    { title: "Hussein Nasser — database playlists", url: "https://www.youtube.com/@hnasr/playlists", kind: "video" },
    { title: "Build: embed SQLite in a Python or Node app", url: "/jobs?skill=SQLite", kind: "project" },
  ],
  MongoDB: [
    { title: "MongoDB docs", url: "https://www.mongodb.com/docs/manual/", kind: "docs" },
    { title: "MongoDB University (free)", url: "https://learn.mongodb.com/", kind: "course" },
    { title: "MongoDB — Developer Center articles", url: "https://www.mongodb.com/developer/", kind: "book" },
    { title: "The Net Ninja — MongoDB playlist", url: "https://www.youtube.com/playlist?list=PL4cUxeGkcC9jpvoYriLI0bY8DOgWZfi6u", kind: "video" },
    { title: "Build: REST API backed by MongoDB", url: "/jobs?skill=MongoDB", kind: "project" },
  ],
  Redis: [
    { title: "Redis docs", url: "https://redis.io/docs/", kind: "docs" },
    { title: "Redis University (free)", url: "https://university.redis.com/", kind: "course" },
    { title: "Hussein Nasser — Redis Crash Course", url: "https://www.youtube.com/watch?v=V7FPk4J10KI", kind: "video" },
    { title: "Redis howtos + patterns", url: "https://redis.io/learn/howtos", kind: "book" },
    { title: "Build: add Redis cache to an API", url: "/jobs?skill=Redis", kind: "project" },
  ],
  Elasticsearch: [
    { title: "Elasticsearch — Getting Started", url: "https://www.elastic.co/guide/en/elasticsearch/reference/current/getting-started.html", kind: "docs" },
    { title: "Elastic — free training", url: "https://www.elastic.co/training/free", kind: "course" },
    { title: "Official Elastic — playlists", url: "https://www.youtube.com/@officialelastic/playlists", kind: "video" },
    { title: "Elasticsearch: The Definitive Guide (free online)", url: "https://www.elastic.co/guide/en/elasticsearch/guide/current/index.html", kind: "book" },
    { title: "Build: search over your job dataset", url: "/jobs?skill=Elasticsearch", kind: "project" },
  ],
  Cassandra: [
    { title: "Cassandra docs", url: "https://cassandra.apache.org/doc/latest/", kind: "docs" },
    { title: "DataStax — learn", url: "https://www.datastax.com/learn", kind: "course" },
    { title: "DataStax Devs — playlists", url: "https://www.youtube.com/@DataStaxDevs/playlists", kind: "video" },
    { title: "Cassandra Data Modeling", url: "https://cassandra.apache.org/doc/latest/cassandra/data_modeling/index.html", kind: "book" },
    { title: "Build: time-series store with Cassandra", url: "/jobs?skill=Cassandra", kind: "project" },
  ],
  DynamoDB: [
    { title: "DynamoDB Developer Guide", url: "https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Introduction.html", kind: "docs" },
    { title: "Alex DeBrie — DynamoDB Guide (free)", url: "https://www.dynamodbguide.com/", kind: "book" },
    { title: "Be A Better Dev — AWS + DynamoDB playlists", url: "https://www.youtube.com/@BeABetterDev/playlists", kind: "video" },
    { title: "AWS DynamoDB workshops", url: "https://workshops.aws/categories/DynamoDB", kind: "project" },
    { title: "Build: serverless API with Lambda + DynamoDB", url: "/jobs?skill=DynamoDB", kind: "project" },
  ],
  "SQL Server": [
    { title: "SQL Server docs", url: "https://learn.microsoft.com/en-us/sql/sql-server/", kind: "docs" },
    { title: "SQL Server Tutorial", url: "https://www.sqlservertutorial.net/", kind: "book" },
    { title: "Brent Ozar — playlists", url: "https://www.youtube.com/@BrentOzar/playlists", kind: "video" },
    { title: "Microsoft Learn — SQL Server path", url: "https://learn.microsoft.com/en-us/training/browse/?products=sql-server", kind: "course" },
    { title: "Build: T-SQL reporting on AdventureWorks", url: "/jobs?skill=SQL+Server", kind: "project" },
  ],

  // ─── Cloud ──────────────────────────────────────────────────────────
  AWS: [
    { title: "AWS docs", url: "https://docs.aws.amazon.com/", kind: "docs" },
    { title: "AWS Skill Builder (free)", url: "https://skillbuilder.aws/", kind: "course" },
    { title: "AWS Builder's Library (free)", url: "https://aws.amazon.com/builders-library/", kind: "book" },
    { title: "freeCodeCamp — AWS Cloud Practitioner (14h)", url: "https://www.youtube.com/watch?v=NhDYbskXRgc", kind: "video" },
    { title: "Be A Better Dev — AWS playlists", url: "https://www.youtube.com/@BeABetterDev/playlists", kind: "video" },
    { title: "AWS Workshops (hands-on)", url: "https://workshops.aws/", kind: "project" },
  ],
  GCP: [
    { title: "GCP docs", url: "https://cloud.google.com/docs", kind: "docs" },
    { title: "Google Cloud Skills Boost", url: "https://www.cloudskillsboost.google/", kind: "course" },
    { title: "Google Cloud Tech — playlists", url: "https://www.youtube.com/@googlecloudtech/playlists", kind: "video" },
    { title: "GCP architecture framework", url: "https://cloud.google.com/architecture/framework", kind: "book" },
    { title: "Build: deploy app to Cloud Run + Cloud SQL", url: "/jobs?skill=GCP", kind: "project" },
  ],
  Azure: [
    { title: "Azure docs", url: "https://learn.microsoft.com/en-us/azure/", kind: "docs" },
    { title: "Microsoft Learn — Azure Fundamentals", url: "https://learn.microsoft.com/en-us/training/paths/azure-fundamentals/", kind: "course" },
    { title: "John Savill — Azure playlists", url: "https://www.youtube.com/@NTFAQGuy/playlists", kind: "video" },
    { title: "Azure Architecture Center", url: "https://learn.microsoft.com/en-us/azure/architecture/", kind: "book" },
    { title: "Build: deploy app to App Service + Azure SQL", url: "/jobs?skill=Azure", kind: "project" },
  ],
  Cloudflare: [
    { title: "Cloudflare Workers docs", url: "https://developers.cloudflare.com/workers/", kind: "docs" },
    { title: "Cloudflare Developer docs", url: "https://developers.cloudflare.com/", kind: "book" },
    { title: "Cloudflare Developers — playlists", url: "https://www.youtube.com/@CloudflareDevelopers/playlists", kind: "video" },
    { title: "Workers examples", url: "https://developers.cloudflare.com/workers/examples/", kind: "course" },
    { title: "Build: edge API with Workers + KV/R2", url: "/jobs?skill=Cloudflare", kind: "project" },
  ],
  Vercel: [
    { title: "Vercel docs", url: "https://vercel.com/docs", kind: "docs" },
    { title: "Vercel templates", url: "https://vercel.com/templates", kind: "book" },
    { title: "Vercel — YouTube channel", url: "https://www.youtube.com/@VercelHQ/playlists", kind: "video" },
    { title: "Next.js Learn (free interactive)", url: "https://nextjs.org/learn", kind: "course" },
    { title: "Build: deploy this app to Vercel", url: "/jobs?skill=Vercel", kind: "project" },
  ],
  Heroku: [
    { title: "Heroku Dev Center", url: "https://devcenter.heroku.com/", kind: "docs" },
    { title: "Twelve-Factor App (free)", url: "https://12factor.net/", kind: "book" },
    { title: "Heroku platform guides", url: "https://devcenter.heroku.com/categories/heroku-architecture", kind: "course" },
    { title: "Heroku — playlists", url: "https://www.youtube.com/@HerokuOfficial/playlists", kind: "video" },
    { title: "Build: deploy a small API to Heroku", url: "/jobs?skill=Heroku", kind: "project" },
  ],

  // ─── DevOps ─────────────────────────────────────────────────────────
  Docker: [
    { title: "Docker docs — Get Started", url: "https://docs.docker.com/get-started/", kind: "docs" },
    { title: "Docker Curriculum (free)", url: "https://docker-curriculum.com/", kind: "book" },
    { title: "TechWorld with Nana — Docker tutorial (3h)", url: "https://www.youtube.com/watch?v=3c-iBn73dDE", kind: "video" },
    { title: "The Net Ninja — Docker Crash Course playlist", url: "https://www.youtube.com/playlist?list=PL4cUxeGkcC9hxjeEtdHFNYMtCpjNBm3h7", kind: "video" },
    { title: "Build: containerize your job scraper", url: "/jobs?q=docker", kind: "project" },
  ],
  Kubernetes: [
    { title: "Kubernetes tutorials", url: "https://kubernetes.io/docs/tutorials/", kind: "docs" },
    { title: "Kubernetes the Hard Way", url: "https://github.com/kelseyhightower/kubernetes-the-hard-way", kind: "book" },
    { title: "TechWorld with Nana — K8s tutorial (4h)", url: "https://www.youtube.com/watch?v=X48VuDVv0do", kind: "video" },
    { title: "TechWorld with Nana — DevOps Bootcamp playlist", url: "https://www.youtube.com/playlist?list=PLy7NrYWoggjwwEpZO8sscD9X6EH39njz6", kind: "video" },
    { title: "Killercoda — interactive K8s scenarios", url: "https://killercoda.com/kubernetes", kind: "project" },
  ],
  Terraform: [
    { title: "Terraform tutorials (HashiCorp)", url: "https://developer.hashicorp.com/terraform/tutorials", kind: "course" },
    { title: "Terraform docs", url: "https://developer.hashicorp.com/terraform/docs", kind: "docs" },
    { title: "freeCodeCamp — Terraform AWS course", url: "https://www.youtube.com/watch?v=SLB_c_ayRMo", kind: "video" },
    { title: "Terraform Up & Running examples", url: "https://github.com/brikis98/terraform-up-and-running-code", kind: "book" },
    { title: "Build: provision a 3-tier AWS stack", url: "/jobs?skill=Terraform", kind: "project" },
  ],
  Ansible: [
    { title: "Ansible Getting Started", url: "https://docs.ansible.com/ansible/latest/getting_started/index.html", kind: "docs" },
    { title: "Ansible tips + tricks", url: "https://docs.ansible.com/ansible/latest/tips_tricks/ansible_tips_tricks.html", kind: "book" },
    { title: "Jeff Geerling — Ansible 101 playlist", url: "https://www.youtube.com/playlist?list=PL2_OBreMn7FqZkvMYt6ATmgC0KAGGJNAN", kind: "video" },
    { title: "LearnLinuxTV — playlists", url: "https://www.youtube.com/@LearnLinuxTV/playlists", kind: "video" },
    { title: "Build: provision Linux servers with playbooks", url: "/jobs?skill=Ansible", kind: "project" },
  ],
  Jenkins: [
    { title: "Jenkins User Handbook", url: "https://www.jenkins.io/doc/book/", kind: "docs" },
    { title: "Jenkins Pipeline reference", url: "https://www.jenkins.io/doc/book/pipeline/", kind: "book" },
    { title: "TechWorld with Nana — Jenkins tutorial", url: "https://www.youtube.com/watch?v=6YZvp2GwT0A", kind: "video" },
    { title: "DevOps Journey — playlists", url: "https://www.youtube.com/@devopsjourney1/playlists", kind: "video" },
    { title: "Build: declarative pipeline for a small repo", url: "/jobs?skill=Jenkins", kind: "project" },
  ],
  "GitHub Actions": [
    { title: "GitHub Actions docs", url: "https://docs.github.com/en/actions", kind: "docs" },
    { title: "Awesome GitHub Actions", url: "https://github.com/sdras/awesome-actions", kind: "book" },
    { title: "GitHub — playlists", url: "https://www.youtube.com/@GitHub/playlists", kind: "video" },
    { title: "Fireship — Actions in 100s", url: "https://www.youtube.com/watch?v=eB0nUzAI7M8", kind: "video" },
    { title: "Build: CI for this repo (lint + tests + deploy)", url: "/jobs?skill=GitHub+Actions", kind: "project" },
  ],
  "GitLab CI": [
    { title: "GitLab CI/CD docs", url: "https://docs.gitlab.com/ee/ci/", kind: "docs" },
    { title: "GitLab CI/CD examples", url: "https://docs.gitlab.com/ee/ci/examples/", kind: "book" },
    { title: "GitLab Unfiltered — playlists", url: "https://www.youtube.com/@GitLabUnfiltered/playlists", kind: "video" },
    { title: "DevOps Journey — playlists", url: "https://www.youtube.com/@devopsjourney1/playlists", kind: "video" },
    { title: "Build: build + test + deploy via .gitlab-ci.yml", url: "/jobs?skill=GitLab+CI", kind: "project" },
  ],
  Linux: [
    { title: "Linux Journey", url: "https://linuxjourney.com/", kind: "course" },
    { title: "The Linux Command Line (free book)", url: "https://linuxcommand.org/tlcl.php", kind: "book" },
    { title: "Linux man pages", url: "https://man7.org/linux/man-pages/", kind: "docs" },
    { title: "Joe Collins — Linux Command Line playlist", url: "https://www.youtube.com/playlist?list=PLS1QulWo1RIb9WVQGJ_vh-RQusbZgO_As", kind: "video" },
    { title: "OverTheWire: Bandit (practice)", url: "https://overthewire.org/wargames/bandit/", kind: "project" },
  ],
  Nginx: [
    { title: "Nginx Beginner's Guide", url: "https://nginx.org/en/docs/beginners_guide.html", kind: "docs" },
    { title: "Nginx full docs", url: "https://nginx.org/en/docs/", kind: "book" },
    { title: "Hussein Nasser — Nginx playlists", url: "https://www.youtube.com/@hnasr/playlists", kind: "video" },
    { title: "Nginx Playground (Julia Evans)", url: "https://nginx-playground.wizardzines.com/", kind: "project" },
    { title: "Build: reverse-proxy + TLS in front of an app", url: "/jobs?skill=Nginx", kind: "project" },
  ],
  "CI/CD": [
    { title: "GitHub Actions docs", url: "https://docs.github.com/en/actions/learn-github-actions", kind: "docs" },
    { title: "Martin Fowler — Continuous Integration", url: "https://martinfowler.com/articles/continuousIntegration.html", kind: "book" },
    { title: "Google SRE — Release Engineering chapter", url: "https://sre.google/sre-book/release-engineering/", kind: "book" },
    { title: "TechWorld with Nana — DevOps Bootcamp playlist", url: "https://www.youtube.com/playlist?list=PLy7NrYWoggjwwEpZO8sscD9X6EH39njz6", kind: "video" },
    { title: "Build: add full CI/CD to a real repo", url: "/jobs?skill=CI%2FCD", kind: "project" },
  ],

  // ─── Data / AI ──────────────────────────────────────────────────────
  Pandas: [
    { title: "Pandas docs — user guide", url: "https://pandas.pydata.org/docs/user_guide/", kind: "docs" },
    { title: "10 minutes to pandas", url: "https://pandas.pydata.org/docs/user_guide/10min.html", kind: "course" },
    { title: "Python Data Science Handbook (free)", url: "https://jakevdp.github.io/PythonDataScienceHandbook/", kind: "book" },
    { title: "freeCodeCamp — Data Analysis with Python playlist", url: "https://www.youtube.com/playlist?list=PLWKjhJtqVAblvI1i46ScbKV2jH1gdL7VQ", kind: "video" },
    { title: "Kaggle — Pandas micro-course", url: "https://www.kaggle.com/learn/pandas", kind: "course" },
    { title: "Build: EDA on a public dataset", url: "/jobs?skill=Pandas", kind: "project" },
  ],
  NumPy: [
    { title: "NumPy Quickstart", url: "https://numpy.org/doc/stable/user/quickstart.html", kind: "docs" },
    { title: "From Python to NumPy (free book)", url: "https://www.labri.fr/perso/nrougier/from-python-to-numpy/", kind: "book" },
    { title: "Python Data Science Handbook — NumPy", url: "https://jakevdp.github.io/PythonDataScienceHandbook/02.00-introduction-to-numpy.html", kind: "book" },
    { title: "freeCodeCamp — NumPy course (Keith Galli)", url: "https://www.youtube.com/watch?v=QUT1VHiLmmI", kind: "video" },
    { title: "Build: vectorize a slow Python loop", url: "/jobs?skill=NumPy", kind: "project" },
  ],
  Spark: [
    { title: "Spark — Quick Start", url: "https://spark.apache.org/docs/latest/quick-start.html", kind: "docs" },
    { title: "Spark — programming guides", url: "https://spark.apache.org/docs/latest/", kind: "book" },
    { title: "Databricks — free training", url: "https://www.databricks.com/learn/training", kind: "course" },
    { title: "Databricks — playlists", url: "https://www.youtube.com/@Databricks/playlists", kind: "video" },
    { title: "Build: ETL pipeline with PySpark", url: "/jobs?skill=Spark", kind: "project" },
  ],
  Kafka: [
    { title: "Apache Kafka — Quickstart", url: "https://kafka.apache.org/quickstart", kind: "docs" },
    { title: "Confluent — Kafka 101", url: "https://developer.confluent.io/courses/apache-kafka/events/", kind: "course" },
    { title: "Confluent — Apache Kafka 101 playlist", url: "https://www.youtube.com/playlist?list=PLf38f5LhQtheK16nwnCYFqH23WUUvZfSb", kind: "video" },
    { title: "Kafka — The Definitive Guide (free PDF, Confluent)", url: "https://www.confluent.io/resources/kafka-the-definitive-guide-v2/", kind: "book" },
    { title: "Build: event pipeline with producers + consumers", url: "/jobs?skill=Kafka", kind: "project" },
  ],
  Airflow: [
    { title: "Airflow docs", url: "https://airflow.apache.org/docs/apache-airflow/stable/start.html", kind: "docs" },
    { title: "Astronomer — Airflow guides (free)", url: "https://www.astronomer.io/docs/learn/", kind: "book" },
    { title: "Data with Marc (Marc Lamberti) — playlists", url: "https://www.youtube.com/@MarcLamberti/playlists", kind: "video" },
    { title: "Airflow example DAGs", url: "https://github.com/apache/airflow/tree/main/airflow/example_dags", kind: "course" },
    { title: "Build: scheduled DAG that scrapes + loads jobs", url: "/jobs?skill=Airflow", kind: "project" },
  ],
  Snowflake: [
    { title: "Snowflake docs", url: "https://docs.snowflake.com/", kind: "docs" },
    { title: "Snowflake — Hands-on Essentials", url: "https://learn.snowflake.com/", kind: "course" },
    { title: "Snowflake Inc — playlists", url: "https://www.youtube.com/@SnowflakeInc/playlists", kind: "video" },
    { title: "Snowflake Quickstarts (hands-on)", url: "https://quickstarts.snowflake.com/", kind: "book" },
    { title: "Build: load + query a free dataset on Snowflake trial", url: "/jobs?skill=Snowflake", kind: "project" },
  ],
  BigQuery: [
    { title: "BigQuery — quickstarts", url: "https://cloud.google.com/bigquery/docs/quickstarts", kind: "docs" },
    { title: "BigQuery best practices", url: "https://cloud.google.com/bigquery/docs/best-practices-performance-overview", kind: "book" },
    { title: "Google Cloud Tech — playlists", url: "https://www.youtube.com/@googlecloudtech/playlists", kind: "video" },
    { title: "BigQuery free public datasets", url: "https://cloud.google.com/bigquery/public-data", kind: "course" },
    { title: "Build: dashboard powered by a public dataset", url: "/jobs?skill=BigQuery", kind: "project" },
  ],
  ETL: [
    { title: "dbt — Learn (free)", url: "https://learn.getdbt.com/", kind: "course" },
    { title: "dbt docs", url: "https://docs.getdbt.com/", kind: "docs" },
    { title: "DDIA — book site", url: "https://dataintensive.net/", kind: "book" },
    { title: "Seattle Data Guy — playlists", url: "https://www.youtube.com/@SeattleDataGuy/playlists", kind: "video" },
    { title: "Build: extract → transform → load a real dataset", url: "/jobs?skill=ETL", kind: "project" },
  ],
  TensorFlow: [
    { title: "TensorFlow tutorials", url: "https://www.tensorflow.org/tutorials", kind: "docs" },
    { title: "TF guide", url: "https://www.tensorflow.org/guide", kind: "book" },
    { title: "TensorFlow — playlists", url: "https://www.youtube.com/@TensorFlow/playlists", kind: "video" },
    { title: "freeCodeCamp — TF 2.0 full course", url: "https://www.youtube.com/watch?v=tPYj3fFJGjk", kind: "video" },
    { title: "Build: train + serve a model with SavedModel", url: "/jobs?skill=TensorFlow", kind: "project" },
  ],
  PyTorch: [
    { title: "PyTorch — 60-min Blitz", url: "https://pytorch.org/tutorials/beginner/deep_learning_60min_blitz.html", kind: "docs" },
    { title: "PyTorch docs", url: "https://pytorch.org/docs/stable/index.html", kind: "book" },
    { title: "freeCodeCamp — PyTorch full course (Daniel Bourke, 26h)", url: "https://www.youtube.com/watch?v=V_xro1bcAuA", kind: "video" },
    { title: "freeCodeCamp — PyTorch playlist", url: "https://www.youtube.com/playlist?list=PLLrn53dusOtlJv4mPJM46Ti4ic_FDbQSL", kind: "video" },
    { title: "Build: train + fine-tune a vision or NLP model", url: "/jobs?skill=PyTorch", kind: "project" },
  ],
  "scikit-learn": [
    { title: "scikit-learn user guide", url: "https://scikit-learn.org/stable/user_guide.html", kind: "docs" },
    { title: "scikit-learn examples", url: "https://scikit-learn.org/stable/auto_examples/index.html", kind: "book" },
    { title: "StatQuest — Machine Learning playlist", url: "https://www.youtube.com/playlist?list=PLng25Lwn1Xd11NzZFwn8ZyLr-cwWvZi59", kind: "video" },
    { title: "Kaggle — Intro to ML", url: "https://www.kaggle.com/learn/intro-to-machine-learning", kind: "course" },
    { title: "Build: classification project end-to-end", url: "/jobs?skill=scikit-learn", kind: "project" },
  ],
  LangChain: [
    { title: "LangChain docs", url: "https://python.langchain.com/docs/get_started/introduction", kind: "docs" },
    { title: "LangChain conceptual guide", url: "https://python.langchain.com/docs/concepts/", kind: "book" },
    { title: "LangChain — playlists", url: "https://www.youtube.com/@LangChain/playlists", kind: "video" },
    { title: "DeepLearning.AI — LangChain short courses (free)", url: "https://www.deeplearning.ai/short-courses/langchain-for-llm-application-development/", kind: "course" },
    { title: "Build: RAG chatbot over your own docs", url: "/jobs?skill=LangChain", kind: "project" },
  ],
  "Machine Learning": [
    { title: "scikit-learn user guide", url: "https://scikit-learn.org/stable/user_guide.html", kind: "docs" },
    { title: "Coursera — Andrew Ng ML Specialization (free audit)", url: "https://www.coursera.org/specializations/machine-learning-introduction", kind: "course" },
    { title: "An Introduction to Statistical Learning (free PDF)", url: "https://www.statlearning.com/", kind: "book" },
    { title: "StatQuest — Machine Learning playlist", url: "https://www.youtube.com/playlist?list=PLng25Lwn1Xd11NzZFwn8ZyLr-cwWvZi59", kind: "video" },
    { title: "Kaggle Learn — micro-courses", url: "https://www.kaggle.com/learn", kind: "course" },
    { title: "Build: end-to-end ML project on Kaggle", url: "/jobs?skill=Machine+Learning", kind: "project" },
  ],
  "Deep Learning": [
    { title: "fast.ai — Practical Deep Learning", url: "https://course.fast.ai/", kind: "course" },
    { title: "Deep Learning book (Goodfellow, free)", url: "https://www.deeplearningbook.org/", kind: "book" },
    { title: "Andrej Karpathy — Zero to Hero playlist", url: "https://www.youtube.com/playlist?list=PLXYLzZ3XzIbi4lL43O6fIU_ojuZwBO6vi", kind: "video" },
    { title: "3Blue1Brown — Neural Networks playlist", url: "https://www.youtube.com/playlist?list=PLZZWrBYkx7Otcjr3eCLZDCgfpqnxMY29s", kind: "video" },
    { title: "Build: train a CNN + a Transformer from scratch", url: "/jobs?skill=Deep+Learning", kind: "project" },
  ],
  NLP: [
    { title: "Hugging Face — NLP course (free)", url: "https://huggingface.co/learn/nlp-course/chapter1/1", kind: "course" },
    { title: "Stanford CS224N — NLP w/ Deep Learning", url: "https://web.stanford.edu/class/cs224n/", kind: "book" },
    { title: "Hugging Face — Transformers playlist", url: "https://www.youtube.com/playlist?list=PLsJsyE4MbtiqsQgqjUVsF6jx_eqy53GRq", kind: "video" },
    { title: "spaCy 101 (docs)", url: "https://spacy.io/usage/spacy-101", kind: "docs" },
    { title: "Build: fine-tune a HF model for a task", url: "/jobs?skill=NLP", kind: "project" },
  ],

  // ─── Mobile ─────────────────────────────────────────────────────────
  "React Native": [
    { title: "React Native docs", url: "https://reactnative.dev/docs/getting-started", kind: "docs" },
    { title: "Expo docs", url: "https://docs.expo.dev/", kind: "book" },
    { title: "The Net Ninja — React Native playlist", url: "https://www.youtube.com/playlist?list=PL4cUxeGkcC9ixPU-QkScoRBVxtPPzVjrQ", kind: "video" },
    { title: "notJust․dev — playlists", url: "https://www.youtube.com/@notjustdev/playlists", kind: "video" },
    { title: "Build: cross-platform app with Expo + EAS", url: "/jobs?skill=React+Native", kind: "project" },
  ],
  Flutter: [
    { title: "Flutter docs", url: "https://docs.flutter.dev/", kind: "docs" },
    { title: "Flutter Codelabs", url: "https://docs.flutter.dev/codelabs", kind: "course" },
    { title: "The Net Ninja — Flutter Beginners playlist", url: "https://www.youtube.com/playlist?list=PLzAGFfNxKFubb5MQiKACcKCPN_31SHERu", kind: "video" },
    { title: "Flutter — official playlists", url: "https://www.youtube.com/@flutterdev/playlists", kind: "video" },
    { title: "Build: full Flutter app + Firebase", url: "/jobs?skill=Flutter", kind: "project" },
  ],
  Android: [
    { title: "Android Developers — courses", url: "https://developer.android.com/courses", kind: "docs" },
    { title: "Jetpack Compose Pathway", url: "https://developer.android.com/courses/jetpack-compose/course", kind: "course" },
    { title: "Philipp Lackner — Jetpack Compose playlist", url: "https://www.youtube.com/playlist?list=PLQkwcJG4YTCSpJ2NLhDTHhi6XBNfk9WiC", kind: "video" },
    { title: "Android Developers — playlists", url: "https://www.youtube.com/@AndroidDevelopers/playlists", kind: "video" },
    { title: "Build: Compose app with Room + Retrofit", url: "/jobs?skill=Android", kind: "project" },
  ],

  // ─── Tools / methodology ────────────────────────────────────────────
  Git: [
    { title: "Pro Git (free book)", url: "https://git-scm.com/book/en/v2", kind: "book" },
    { title: "Git docs", url: "https://git-scm.com/docs", kind: "docs" },
    { title: "Learn Git Branching (interactive)", url: "https://learngitbranching.js.org/", kind: "course" },
    { title: "The Net Ninja — Git & GitHub for Beginners playlist", url: "https://www.youtube.com/playlist?list=PLqyUgadpThTLN0yRrqWHB_McNK5LwTgh1", kind: "video" },
    { title: "Programming with Mosh — Git in 1 hour", url: "https://www.youtube.com/watch?v=8JJ101D3knE", kind: "video" },
    { title: "Oh My Git! (game)", url: "https://ohmygit.org/", kind: "project" },
  ],
  GitHub: [
    { title: "GitHub Docs", url: "https://docs.github.com/en", kind: "docs" },
    { title: "GitHub Skills (interactive)", url: "https://skills.github.com/", kind: "course" },
    { title: "The Net Ninja — Git & GitHub for Beginners playlist", url: "https://www.youtube.com/playlist?list=PLqyUgadpThTLN0yRrqWHB_McNK5LwTgh1", kind: "video" },
    { title: "GitHub Flow guide", url: "https://docs.github.com/en/get-started/quickstart/github-flow", kind: "book" },
    { title: "Build: open-source PR to a real repo", url: "/jobs?skill=GitHub", kind: "project" },
  ],
  GitLab: [
    { title: "GitLab docs", url: "https://docs.gitlab.com/", kind: "docs" },
    { title: "GitLab Handbook (free)", url: "https://handbook.gitlab.com/", kind: "book" },
    { title: "GitLab Unfiltered — playlists", url: "https://www.youtube.com/@GitLabUnfiltered/playlists", kind: "video" },
    { title: "GitLab tutorials", url: "https://docs.gitlab.com/ee/tutorials/", kind: "course" },
    { title: "Build: project + MR workflow + CI on GitLab", url: "/jobs?skill=GitLab", kind: "project" },
  ],
  Jira: [
    { title: "Atlassian — Jira guide", url: "https://www.atlassian.com/software/jira/guides/getting-started/overview", kind: "docs" },
    { title: "Atlassian — Agile coach", url: "https://www.atlassian.com/agile", kind: "book" },
    { title: "Atlassian — playlists", url: "https://www.youtube.com/@Atlassian/playlists", kind: "video" },
    { title: "JQL reference", url: "https://support.atlassian.com/jira-software-cloud/docs/use-advanced-search-with-jira-query-language-jql/", kind: "course" },
    { title: "Set up: a sprint board for a real project", url: "/jobs?skill=Jira", kind: "project" },
  ],
  Figma: [
    { title: "Figma — Learn Design", url: "https://www.figma.com/resources/learn-design/", kind: "docs" },
    { title: "Figma Help Center", url: "https://help.figma.com/hc/en-us", kind: "book" },
    { title: "Figma — official playlists", url: "https://www.youtube.com/@Figma/playlists", kind: "video" },
    { title: "DesignCourse — playlists", url: "https://www.youtube.com/@DesignCourse/playlists", kind: "video" },
    { title: "Build: redesign a real product screen + prototype", url: "/jobs?skill=Figma", kind: "project" },
  ],
  Agile: [
    { title: "Agile Manifesto", url: "https://agilemanifesto.org/", kind: "docs" },
    { title: "Atlassian — Agile coach", url: "https://www.atlassian.com/agile", kind: "course" },
    { title: "Martin Fowler — bliki on Agile", url: "https://martinfowler.com/agile.html", kind: "book" },
    { title: "Mountain Goat Software — playlists", url: "https://www.youtube.com/@MountainGoatSoftware/playlists", kind: "video" },
    { title: "Apply: run a 2-week iteration on a side project", url: "/jobs?skill=Agile", kind: "project" },
  ],
  Scrum: [
    { title: "Scrum Guide (free)", url: "https://scrumguides.org/scrum-guide.html", kind: "docs" },
    { title: "Scrum.org — resources", url: "https://www.scrum.org/resources", kind: "book" },
    { title: "Mountain Goat Software — playlists", url: "https://www.youtube.com/@MountainGoatSoftware/playlists", kind: "video" },
    { title: "Atlassian — Scrum guide", url: "https://www.atlassian.com/agile/scrum", kind: "course" },
    { title: "Apply: 1 sprint with backlog + review + retro", url: "/jobs?skill=Scrum", kind: "project" },
  ],
  TDD: [
    { title: "Martin Fowler — TestDrivenDevelopment", url: "https://martinfowler.com/bliki/TestDrivenDevelopment.html", kind: "docs" },
    { title: "James Shore — Art of Agile (free chapters)", url: "https://www.jamesshore.com/v2/books/aoad2", kind: "book" },
    { title: "Continuous Delivery — playlists", url: "https://www.youtube.com/@continuousdelivery/playlists", kind: "video" },
    { title: "Build: refactor a project using red-green-refactor", url: "/jobs?skill=TDD", kind: "project" },
  ],
  Microservices: [
    { title: "microservices.io patterns", url: "https://microservices.io/patterns/index.html", kind: "docs" },
    { title: "Martin Fowler — Microservices article", url: "https://martinfowler.com/articles/microservices.html", kind: "book" },
    { title: "Hussein Nasser — playlists", url: "https://www.youtube.com/@hnasr/playlists", kind: "video" },
    { title: "InfoQ — playlists", url: "https://www.youtube.com/@InfoQ/playlists", kind: "video" },
    { title: "Build: 2-service system with async messaging", url: "/jobs?skill=Microservices", kind: "project" },
  ],

  // ─── Extras (used elsewhere in app) ─────────────────────────────────
  Communication: [
    { title: "Write the Docs — guide", url: "https://www.writethedocs.org/guide/", kind: "docs" },
    { title: "Google — Technical Writing Courses (free)", url: "https://developers.google.com/tech-writing", kind: "course" },
    { title: "Patrick Winston — How to Speak (MIT, video)", url: "https://www.youtube.com/watch?v=Unzc731iCUY", kind: "video" },
    { title: "ADR template + examples", url: "https://github.com/joelparkerhenderson/architecture-decision-record", kind: "book" },
    { title: "Practice: write one ADR for a real project decision", url: "/jobs?skill=Communication", kind: "project" },
  ],
  "Problem Solving": [
    { title: "NeetCode 150 (free)", url: "https://neetcode.io/practice", kind: "course" },
    { title: "LeetCode patterns", url: "https://seanprashad.com/leetcode-patterns/", kind: "docs" },
    { title: "Algorithms (Princeton, Sedgewick, free)", url: "https://algs4.cs.princeton.edu/home/", kind: "book" },
    { title: "NeetCode — Blind 75 playlist", url: "https://www.youtube.com/playlist?list=PL2jJagmWP7hz5x_2ykNLhKkXyiO04fwip", kind: "video" },
    { title: "Practice: 1 medium per day for a month", url: "/jobs?skill=Problem+Solving", kind: "project" },
  ],
};

export function resourcesFor(skill: string): Resource[] {
  return RESOURCES[skill] ?? [];
}
